---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: yukulab-infra
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/YukkuriLaboratory/infra
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yukulab-tenant-setup
  namespace: flux-system
spec:
  wait: true
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/main/tenants/base
  prune: true
  postBuild:
    substitute:
      tenant_name: yukulab
      quota_requests_cpu: "4"
      quota_requests_memory: 8Gi
      quota_limits_cpu: "8"
      quota_limits_memory: 16Gi
      quota_pvc: "10"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yukulab-workloads
  namespace: flux-system
spec:
  suspend: true
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: yukulab-infra
  path: ./
  prune: true
  targetNamespace: yukulab
  serviceAccountName: yukulab-deployer
  dependsOn:
    - name: yukulab-tenant-setup
  decryption:
    provider: sops
    secretRef:
      name: sops-age-yukulab
