# SPDX-License-Identifier: AGPL-3.0-or-later

svc:
  shard:
    replicas: 4
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
  router:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
  maxConcurrentRequests: 256
