---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
  namespace: fluxer
data:
  Caddyfile: |
    :80 {
        encode zstd gzip

        handle /_health {
            respond "OK" 200
        }

        handle_path /api/* {
            reverse_proxy api:8080
        }

        handle /gateway {
            rewrite * /
            reverse_proxy gateway:8080
        }

        handle_path /gateway/* {
            reverse_proxy gateway:8080
        }

        handle_path /media/* {
            reverse_proxy media-proxy:8080
        }

        handle /admin {
            rewrite * /
            reverse_proxy admin:8080
        }

        handle_path /admin/* {
            reverse_proxy admin:8080
        }

        @staticAssets path /fonts/* /web/* /emoji/* /libs/* /avatars/* /badges/* /desktop/* /embeds/*
        handle @staticAssets {
            reverse_proxy static-proxy:8080
        }

        handle /.well-known/* {
            reverse_proxy api:8080
        }

        handle /sw.js {
            reverse_proxy app-proxy:8080 {
                header_down Cache-Control "no-cache, no-store"
                header_down CDN-Cache-Control "no-cache"
            }
        }

        handle {
            reverse_proxy app-proxy:8080
        }
    }

    :8088 {
        handle_path /api/* {
            reverse_proxy api:8080
        }
    }
