---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
  namespace: fluxer
data:
  Caddyfile: |
    {
        servers :80 {
            trusted_proxies static 10.244.0.0/16
        }
        servers :8088 {
            trusted_proxies static 10.244.0.0/16
        }
    }

    :80 {
        @notSW not path /sw.js
        encode @notSW zstd gzip

        handle /_health {
            respond "OK" 200
        }

        handle_path /api/* {
            reverse_proxy api:8080
        }

        handle /gateway {
            rewrite * /
            reverse_proxy gateway:8080
        }

        handle_path /gateway/* {
            reverse_proxy gateway:8080
        }

        handle_path /media/* {
            reverse_proxy media-proxy:8080
        }

        handle /admin {
            rewrite * /
            reverse_proxy admin:8080
        }

        handle_path /admin/* {
            reverse_proxy admin:8080
        }

        @staticAssets path /fonts/* /emoji/* /libs/* /avatars/* /badges/* /desktop/* /embeds/*
        handle @staticAssets {
            reverse_proxy static-proxy:8080
        }

        handle /web/* {
            reverse_proxy https://fluxerstatic.com {
                header_up Host fluxerstatic.com
            }
        }

        handle /.well-known/* {
            reverse_proxy api:8080
        }

        handle /sw.js {
            header Cache-Control "no-cache, no-store"
            header CDN-Cache-Control "no-cache"
            reverse_proxy app-proxy:8080
        }

        handle /livekit {
            reverse_proxy livekit:7880
        }

        handle_path /livekit/* {
            reverse_proxy livekit:7880
        }

        handle {
            reverse_proxy app-proxy:8080
        }
    }

    :8088 {
        handle_path /api/* {
            reverse_proxy api:8080
        }
    }
