---
apiVersion: v1
kind: Service
metadata:
  name: fluxer-server
  namespace: fluxer
  labels:
    app.kubernetes.io/name: fluxer-server
    app.kubernetes.io/instance: fluxer-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: gateway
      port: 8082
      targetPort: gateway
      protocol: TCP
  selector:
    app.kubernetes.io/name: fluxer-server
    app.kubernetes.io/instance: fluxer-server
