---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxer-app-proxy
  namespace: fluxer
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/helm/app-proxy
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: fluxer-upstream
        namespace: fluxer
      interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: app-proxy
            patch: |-
              - op: remove
                path: /spec/template/spec/imagePullSecrets
  values:
    global:
      registry: ghcr.io/fluxerapp
      namespace: fluxer

    app:
      name: app-proxy
      image: fluxer-app-proxy
      tag: v1
      replicas: 1
      port: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - toliworker-1
                      - toliworker-2
                      - toliworker-3
      env:
        - name: PUBLIC_BOOTSTRAP_API_ENDPOINT
          value: /api
        - name: PUBLIC_BOOTSTRAP_API_PUBLIC_ENDPOINT
          value: https://chat.turtton.net/api
        - name: DISCOVERY_UPSTREAM_URL
          value: http://api.fluxer.svc.cluster.local:8080/.well-known/fluxer
