---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxer-messages
  namespace: fluxer
spec:
  interval: 1h
  chart:
    spec:
      chart: ./deploy/helm/messages
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: fluxer-upstream
        namespace: fluxer
      interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: messages-shard
            patch: |-
              - op: replace
                path: /spec/replicas
                value: 0
  values:
    global:
      registry: ghcr.io/fluxerapp
      namespace: fluxer

    svc:
      name: messages
      image: fluxer-messages
      tag: v1
      nats:
        url: nats://nats.fluxer.svc.cluster.local:4222
      shard:
        replicas: 1
      router:
        replicas: 1
