---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: fluxer
  labels:
    app: meilisearch
spec:
  type: ClusterIP
  selector:
    app: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: http
      protocol: TCP
