apiVersion: v1
kind: Secret
metadata:
    name: fluxer-r2-credentials
    namespace: fluxer
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:3yIegpVxNruX,iv:HQVqCXHcZnj4knJJmUp0OPqVHVFvBHJ1j2FC97Ws3u0=,tag:Sa4Jeyvf/73LgqgKPbWtLQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qmGeVH88lgey,iv:H2czzJvhiVkuB8x89UHyuhf8eHNs9MCmlsgxKOTFww4=,tag:JuvrYSdM+QJG8PUX/5Gsdg==,type:str]
    #ENC[AES256_GCM,data:ORlmdaD6iH4VC5CAqkCMG8cLh8tp6kZYoHnftqJrENmmikvvnXIetpQqVw6e2TW6V87b,iv:P/GIfFkXjD2Uv9T+4WcCLn8DgIllZTWyXySIstehmpI=,tag:NDRhBDGKOfUYOksJPyOneQ==,type:comment]
    ENDPOINT_URL: ENC[AES256_GCM,data:82rYXnwIJSLa,iv:Ccwj9LT3Z70iGWZ0eJoTI/RmQZJhW8NC7y2CKgkjb94=,tag:Pmnvu6X6RVsG9Q6KHZyMTg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcDFlOWxneVJ4Y3dJT3Y5
            ZGFtQkVwRUhuTy8vaFFzTm0xN3RiclROMlNZCjNjMVlUZG1rcU9DVHpqZmd3c3Rl
            c0d2bGF2bk1vMHEyZ0R2N2FISUdxREkKLS0tIFRhY21pc2UrVHpOY2FuUEhaRlRL
            aHFybjFxSHBDTG1ta3Zzak5kcmhjMEEKFEXj9bbISaY7i//4tzrj4OO0MXVoxh8O
            KQU6kOS/rChAtobSkP9My2cjLD/rEv9vHS1y7iwuQiV864D9GgWFGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T03:09:14Z"
    mac: ENC[AES256_GCM,data:Nx88bZCrXkiS0HD9sQFeQNJdGuvwCQX7jNqgs/kOvLfiAiRuD3G4UR+0xZ7nIRKzy2YIO0fknBOTBa6Na1EgCYEhDJz9M98B+D/eCWoHgRQBNmSJdIQwOwn24FG/D3TSTv3MMPVrXL3ivzIaYdbyv94UIXPhuvIBMTbnVSyPi/Q=,iv:GCuMjghGtJ8e9XlMqGXhq2PK9Jg184EeCQTQYPeoqeo=,tag:cIT/+5EdhjyDtT+XTLqsdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
