apiVersion: v1
kind: Secret
metadata:
    name: fluxer-s3-credentials
    namespace: fluxer
type: Opaque
stringData:
    FLUXER_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:c71T8g1cck37eurdtDscrV5Jeo/T9a4aEJyMRU3JLZw=,iv:vUIakwUYwbNUaRVMtXCLRkWwvUeaepmtqshLoBzP7uk=,tag:XB0GjJH1CiauqGy+z4o08A==,type:str]
    FLUXER_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JvY0LdVHy0EdyxqOfJec0nlTjBtoXUIuhRZ6xI4efEQ6oL99XHHzJB9Wed2q7s81aRw8KxKfkzIA79MB5SYSPQ==,iv:XuQjHTL15Rhtsl940yvWIPolZsUs+PKBvMi15ZDXW5w=,tag:1zzTQFWcvwq4S+mJj1KJuQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaWlIUWhpSDJyVkZwTG8r
            cFRFS01LbHVwR2JWNW5OMmV4OGdiWXY5Vm1vCkpSYXFzRWxCc3VhZFFMd1U1aDY3
            T3NLSWtobXptWHRmNEVnMldFZHM3T0EKLS0tIHd1Q00za3doaDUreDMxUmdqU3NR
            SGVScHlMRlBzdGRHb1dtU1FiaWF6UWsKwPBUTCvHCEogwliFtW8vw3tj9mbOnOoX
            5qlUCgG5+qLPerF/B6/JyOP1wQ+rfbMnlGC8YFawU/G14FLpDAH+sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T04:10:36Z"
    mac: ENC[AES256_GCM,data:owhSNBg/IWjym3+1Gzq6VsugNQMpg1sTJeWn8DFLOmWLUsqgTbIpNwqzAhU79H6YoXMOQf5Ll0yI53oFLguKgSMc7rgZxTqfPUz/7IqIWfURRRq+roYBxFG6uh7BGLyeT84uTU/WxmgoERG+DUPPqBIUV0L9IUYqvVPK0od9pr4=,iv:+43lPfuKc5zZ7ew5AxsY0aAfkgrKLYLCRI6LQ3PVPGA=,tag:rOw+SUlIY4na+QoMYzA59w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
