---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: fluxer-db-scheduled
  namespace: fluxer
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: fluxer-db
  method: barmanObjectStore
