---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: fluxer
  labels:
    app: seaweedfs
spec:
  type: ClusterIP
  selector:
    app: seaweedfs
  ports:
    - name: s3
      port: 8333
      targetPort: s3
      protocol: TCP
