---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxer-upstream
  namespace: fluxer
spec:
  interval: 1h
  url: https://github.com/fluxerapp/fluxer
  ref:
    commit: 38b7c634310fb55ab650f7320f15c5dede53b072
  ignore: |
    # Only include deploy/helm/ directory
    /*
    !/deploy/helm/
