apiVersion: v1
kind: Secret
metadata:
    name: atm10-secrets
    namespace: atm10
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KK41CGo/tOb0Vh6OWuifqUsze5NJIET2Ngb3IxwyG3USq8rl/qZF0XBgcHZkVXfPtOfxnpU=,iv:OwyDkKngRHhRk4uJ5SCQpWuZzCiumKxcTIHVBCfsVSc=,tag:ja2emSHa7XGhaBeAQR0Eew==,type:comment]
    #ENC[AES256_GCM,data:vE+4sc1x/SZUTEwvWkTlxHgklkI1WJtRpeExoOrjgQs69HIt9mXsBShme3jLQPdGLojQ1TMukDNqV3JLwVc6DtgS9A==,iv:qxwBSS54lxV6Wnj017TKSbXJpqCZZ9sa4t/pj/5Fqs8=,tag:8k3GTEwPLsN1Yt4fd6Mufw==,type:comment]
    #ENC[AES256_GCM,data:ULD4tuN5jlsXOLjIGPrm3IIunk6RENkbxsPCRTaDPwtv9gFZM9Aow/dnogze9xsNf335EyacCO5YrjCei9uB9kLuV4ePhEIjF6r5Ptg=,iv:ilTugEe9LBy6kr39rWrtcY6Jk/6kRluhQqlkPGtHhog=,tag:hnZS6lGFsC2qK4z1z/WQ+w==,type:comment]
    CF_API_KEY: ENC[AES256_GCM,data:Z2htbA4S84Pk,iv:kSm0ktljfEejvk/8N7NODL9WBox8B1LVhoVjhWdgnDM=,tag:bzdVgxkUYnHhB06P/9zlqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnh4QW1kVVNpanZaMys3
            TkprNmQ1ZzhJbWdudVY1RU9UaG5EVnVZTXdnCk9DazBRU21wM2FRRGdCRXBaS2Jz
            VmZNQ1ZKc1lvanpHZTFwSWtKWkltamsKLS0tIFVXTFFlSVlmNnVjTkFOM25oSkZV
            KzVYYldDc0wyZEdMbnhYZTBYNk5XaGcKrXDqVUe6IYwoebSnmLwfRRrvRoafOqWF
            m6ZF28jX0eoqBbpabuJPoGe9qLHPWKQ4B0TvB4GT4IWCbj7D5TTIlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T03:37:35Z"
    mac: ENC[AES256_GCM,data:s6QmC4mzJR8M9C7qdFSQDxndENNhyA1jF5dKhqqie6ul683K4A0ICOsoWwOcN0gpiHtsHFNltc6k0cjt8YTMXqTvkwHNKvZMW1TfAmJ3x7pQhaz6X7YxKPtpQRKW1Uazw8NCetBPUnOhuFFXyYsAyh1+tSIZqy2NwdJQQKgXsl8=,iv:Zupb+thnyunxZYYGJ5Oe3iuaNXV5m0vO3c/zo6fWQ/Q=,tag:60yk0XJJn+SAcziR/c4/5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
