apiVersion: v1
kind: Secret
metadata:
    name: atm10-secrets
    namespace: atm10
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:DFLvjBtuqRGWBIyJYKiLi8ORsLsUPMAG1EkhpETaOCK+g4ax,iv:NYax9AGr3Uw+dbpdEBkIJMSHDbRMEmc5o8e+6pw5Dg0=,tag:kMGoPzKQZR+7ZhcnU6sgpg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnh4QW1kVVNpanZaMys3
            TkprNmQ1ZzhJbWdudVY1RU9UaG5EVnVZTXdnCk9DazBRU21wM2FRRGdCRXBaS2Jz
            VmZNQ1ZKc1lvanpHZTFwSWtKWkltamsKLS0tIFVXTFFlSVlmNnVjTkFOM25oSkZV
            KzVYYldDc0wyZEdMbnhYZTBYNk5XaGcKrXDqVUe6IYwoebSnmLwfRRrvRoafOqWF
            m6ZF28jX0eoqBbpabuJPoGe9qLHPWKQ4B0TvB4GT4IWCbj7D5TTIlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T04:35:18Z"
    mac: ENC[AES256_GCM,data:CiyNclyLiRtQZvX4j/GxCYJR5yRpl14lonCV5tU0LhlXmhkbCIB4RlhdhR1AAHZ3kS7fZrgkoC7X3e+fm9N/1QrPpckLyG4YTgBjPJFNB8YCZjTxBKpL34GSg1UEcuPfbeFJ7OMrlFHp0Tdtq4Dd88xFXiJygO79uMS5RQgwDbY=,iv:6Ys06G8eKStbTcN8Eleyawg6Eqzxjp1ldTSjyPkcvSc=,tag:niRglAjZGcE5CE1CRFau+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
