apiVersion: v1
kind: Secret
metadata:
    name: atm10-secrets
    namespace: atm10
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:scKGXqqoh3P2gp53GmlIxsmDknA8jS86X59/+WgHYDjCb3AKsCy6mT+oMFhZmVkdxMdu/fjHxrIxF9VT,iv:fOxUoxtv79YdFefZlbnLB3gv8kKqqQzr6m4ZnPEovnc=,tag:YQa6T4un0zUp/1i0+DUpOA==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnh4QW1kVVNpanZaMys3
            TkprNmQ1ZzhJbWdudVY1RU9UaG5EVnVZTXdnCk9DazBRU21wM2FRRGdCRXBaS2Jz
            VmZNQ1ZKc1lvanpHZTFwSWtKWkltamsKLS0tIFVXTFFlSVlmNnVjTkFOM25oSkZV
            KzVYYldDc0wyZEdMbnhYZTBYNk5XaGcKrXDqVUe6IYwoebSnmLwfRRrvRoafOqWF
            m6ZF28jX0eoqBbpabuJPoGe9qLHPWKQ4B0TvB4GT4IWCbj7D5TTIlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T05:26:02Z"
    mac: ENC[AES256_GCM,data:o57ISHyxrEzUINPqiYfuMvZa8kugbz3TmkasFZdqQKM0bRy6Jo0ljW0rjKVUmMyxKgGPSkWZk+E4EGlt+2hIvlPBDaIwQPVBMBOtl4aYYOzGeHRxJ+d35sNXBY2k61jo8L17Z4l2YMtrwSsbvozWkXo5jEjIgAaxDx3M3kp7Sb0=,iv:rtrwbLB58+FHZG6jt86xcGJ3ASLGuvc8+Pu5fm91vG0=,tag:pGOD/UViCvhZwl++IBao2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
