apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atm10
resources:
  - namespace.yaml
  - pvc-v2.yaml
  - deployment.yaml
  - service.yaml
  - podmonitor.yaml
  - hermes-home-rbac.yaml
  - atm10-secrets.sops.yaml
