---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: atm10
  namespace: atm10
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: atm10
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
