apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atm10-data-v2
  namespace: atm10
  labels:
    recurring-job-group.longhorn.io/gameserver: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gameserver
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atm10-downloads-v2
  namespace: atm10
  labels:
    recurring-job-group.longhorn.io/gameserver: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gameserver
  resources:
    requests:
      storage: 500Mi
