apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atm10-data
  namespace: atm10
  annotations:
    data.longhorn.io/number-of-replicas: "2"
    data.longhorn.io/data-locality: best-effort
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
