apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:EkKKwqlOiA+1jd93If/JfTNY5U5k+GPhXYAdWVz59Zdos24zz72PfG+oBKqWSzNGQpSJijCf5Y4BO3O0Wf2C4xkY1gPfJfeP+uHKePruztFJx67hypU4ncRhFk6Ww0tsYPMu0i7CaqXXGXDCyVRvko7P92VbEOiZ5MpZ92yaJUKYQnM97jlJ16EIvmRjPT9E5H9V0SLzi8bKjbiOnKLhsQZLUmHsLA7rklMvH8H6MKMbkejdEIrR3Q==,iv:XsELqve5htM8ir/GO9nxzSzktW0GiQMh1D6u1iBj9Ec=,tag:+q+p/FkIk8tNGPGpdS/fJA==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM3J1ZXdSMTFKOTlTVTYy
            TWxERHZMU2FmelZ5bEpCbGlPSGZOZkRHUFVBCjN1QnRLb0NsK0Z1N0tCaE5sWUt6
            V0l0ajhtTHh2UVYrdkxobFRxTjRCemsKLS0tIERWOXI1RTZobDlEUjRtd24yNS9K
            dzNVcjdtM2dOUjVyUWxieEdDVU1QVGMKEbkGSC38tGrs2kwunoC7Rgdw1S1dhya3
            qfGFZwcx8OxOrmVnWcOpTkc45ofKiWno6efSppClqILpQTgEK9AkJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T10:35:11Z"
    mac: ENC[AES256_GCM,data:vUBz0YIn4nvC8idAM4V/j2cJgpClxB2I8lMidC1JjVD/f5RNT3KwkIDaQ/o6YxDYAx+Fvtuwx0TH5JSs6eQV0bQPvw6zKNTMdFvLdVbO4w+fylaMOAVSRoqBZb4+SZb8K1gxmqJW1ZtZQIGei6+UgoAD8StT2QT1/gckqFf8eTg=,iv:KVdAOmvCv3f6rMUHkNbAIarkh1AIPnYa6QF49Epk44s=,tag:BDYx0WrBNy0maUQMuTvkVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
