monitoring_agent_pve_exporter_api_token_value: ENC[AES256_GCM,data:q2uCiEn1lFutczaaJyWInWeMLhoZrs3AJ9vMtvaD289VS0Sr,iv:oOeouPNgQgndJy/Ns/luSIZnbVynFkDVSWI7NAqN7V0=,tag:VGBCzWCV54OpPn/w2OyXvQ==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:GIbmMql/vkiM3dPYXVlFjAoY8MSaayC7pad4HhastTXw2ugeS4iZTnsx93kBVSyCf4wNn9EJEvfznaiIhis=,iv:djbdeNQ5APraDvKhIvL2VCYRV/tZJNTlVPvEaQZH0nc=,tag:Wa8Ee4IQIeaqhhsiCKshDw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYUdYNjlrcC9DVHIyTnFV
            Yll3Z3IyRk42UHRma0xSZHV3M3ZlUEk4Nm1JCmxzM20zcjRiS0FCMFM4UnludlRJ
            ZXp3RkVWYi83MlBBRWJqeUZ1ZE9vWFEKLS0tIDE2V0kxd08wQTJvUDdOVUpIVTRl
            RDBpdTBKYU5LL3pnRjFwbW5HRkZZMTAKTzjevi3LwHy3T0rdffZ8cP8ezjmTa9f0
            mC2OtJL2n9QRYpx7RVQ6GIy00BknTo0Q00RUt1MaCJrzykAGNXO/KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T14:06:57Z"
    mac: ENC[AES256_GCM,data:/oc9xL4tH+lUWdgHerV5A0BfSor9u8U5t85Ctk4NfluQqPwSHYPtSnu0CWqRM3wCqM7ZMMwSwQIOqoF08zx9NdNoOERmEh4/CAnnm9fpTgLFXI64zVeo0Ayj+pZm1EzPr53NdPz69IjbRhSs7AEyexKG3lReYSlcFyzU2oXs4Ck=,iv:vOEF1dLc1jk94yANbB92JXWOuT5ltI2iypcmnMlJAnE=,tag:H7ksJsV+8O58ucJlx1aPrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
