apiVersion: v1
kind: Secret
metadata:
    name: attic-secrets
    namespace: attic
stringData:
    ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:dOwuC4wtW/1vtJcSGxoqGJQPJJzfqjt+dN4PbS/iJn2UtO7i9xvGYt6gIOKkEzuhy17QwA2Dllm0Fs/W0b5OR05lDYY+n7QIyELviAmFBdLkFKM4jKxH+w==,iv:gVjC3gx4JpeRxCTZNF6AIv6qJq7XzUqV1OXsMBIQYTw=,tag:ErZHojPxee4Zuz4ce2NH5g==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV2c3Y3AwVkFPU1BydHZO
            TlRsOUtsSDBOamJHQWd5R0JEUXBtdFZNR2lVCmViTTlVSmcxd3I1aTAyMGR5eEZ2
            U0ZaK1VYRnVoZUFkOFAxbHdkSThLdmsKLS0tIC85Nk56MTBYSFJhTi9LYjBCVGtn
            cC9wMzZVbkRwcElqNTlQL09MY0crMzQKZj4QB8jbrdCZrT9V60EizwuMM4c4fLyM
            YIueM7oZxtdNQU7CYVBKNEFEXd22fwP5t4Y0E6v3eKDPO/I67gPZQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T05:34:58Z"
    mac: ENC[AES256_GCM,data:2Ex6Eu8T03QSPC+uRkqfGXIWTztrWM66YUPoAHD41Hd3R5UwFPaBRGFWhk8h3V1xIoZMDZWb/m44pgeZ4wi3pRSXMURtyG6Y+YmGn1aEJ4e2yytsy3TsDJFCUiPVBB4IqsK0qD41SIoKitWySafZgQyAazpNq1FizL0Bf5isl8A=,iv:rqdwuMCWLuROMhRdtxc+iXGEIHQ/+a74FqdLHiYwnU8=,tag:M02+cA+G7SGU8lHdJpy1xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
