---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attic-data
  namespace: attic
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
