apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: attic
stringData:
    authkey: ENC[AES256_GCM,data:RsyUB+McQJ71eCQG0J/s9p6998NGUpNdyNFAAUjqQayBeBxWCcHCj8YArkctN/lN1FHGWpDggjJu4h0aStI=,iv:3WsnyyqEPLSvkMn057YiM2t19oOJA0IweBtdZhdyaHI=,tag:QhsOJcivQ9R6iF8tFdMKuQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK013OWpjTWxSem4rc3gx
            Mm1rQ2hCYkdCUG5XSkpZWUNOS1RwMEpadkhRClFEMTZFZTRYZVQxenE5NnpPcGw2
            ZUZobFdnQ21UaUQ0N3FWWG83ZVIrdlkKLS0tIFRsUEZZWFB0cnpzbjBINVBpYlMx
            Wm8vZ2ZpM1U5bVU3eURBWjI3d0VhQjAKI/oME/9++w0oCSett+PsgIFMYr4a6WKZ
            2cIZLvKwprr9x1GsHDqPxNF/xJwPRyV7inyNHzl/N/modBLirABp2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T03:55:51Z"
    mac: ENC[AES256_GCM,data:Q8HurBegPEd2sWspNDxheNdsL2SjVkcSJ1rjovc+4f5CxwDxJqlm9nz6IFzq+gcSub7UXjQb0UVV+vjbADo4YruCDYASw409UtSyUR3v8L6x+fOYN6QZ6Jh9bmpy02jgj0uaSuH5L72agqApClNRqcjjVpQNKeNh02BpSGT9eAs=,iv:8MjG8zxY/kqSZLny/FgcJjEzUGNtFB/gx27j8geFupM=,tag:7ReV58hj0RW9qnJVpBVrzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
