---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-sidecar
  namespace: attic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-sidecar
  namespace: attic
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-sidecar
  namespace: attic
subjects:
  - kind: ServiceAccount
    name: tailscale-sidecar
    namespace: attic
roleRef:
  kind: Role
  name: tailscale-sidecar
  apiGroup: rbac.authorization.k8s.io
