---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: attic
data:
  serve-config.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:8080"
            }
          }
        }
      }
    }
