{{- $clusterEnabled := dig "enabled" false .Values.cluster -}}
{{- $distPort := int (dig "erlangDistribution" "port" 8081 .Values.cluster) -}}
{{- $epmdPort := int (dig "erlangDistribution" "epmdPort" 4369 .Values.cluster) -}}
# SPDX-License-Identifier: AGPL-3.0-or-later

{{include "fluxer.service" (dict "name" "gateway" "values" .Values.gateway "context" .)}}
---
apiVersion: v1
kind: Service
metadata:
  name: fluxer-gateway-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fluxer.labels" . | nindent 4 }}
    {{- include "fluxer.selectorLabels" (dict "name" "gateway" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if $clusterEnabled }}
    - port: {{ $epmdPort }}
      targetPort: epmd
      protocol: TCP
      name: epmd
    - port: {{ $distPort }}
      targetPort: erl-dist
      protocol: TCP
      name: erl-dist
    {{- end }}
  selector:
    {{- if dig "enabled" false .Values.roles }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: fluxer
    {{- else }}
    {{- include "fluxer.selectorLabels" (dict "name" "gateway" "context" .) | nindent 4 }}
    {{- end }}
