# SPDX-License-Identifier: AGPL-3.0-or-later

global:
  namespace: fluxer
  imagePullSecret: ghcr-pull-secret
  registry: ""

mediaProxy:
  image: fluxer-media-proxy
  tag: ""
  replicas: 16
  preserveLiveReplicas: false
  port: 8080
  nsfwServiceEndpoint: 'http://int.flx-nyc-misc1.srv.fluxer.dev:8000'
  env:
    - name: FLUXER_MEDIA_PROXY_MODE
      value: mp
    - name: FLUXER_MEDIA_PROXY_NSFW_THRESHOLD
      value: '0.95'
    - name: FLUXER_MEDIA_PROXY_STORAGE_BACKEND
      value: s3
    - name: FLUXER_MEDIA_PROXY_READ_ONLY
      value: 'true'
    - name: FLUXER_MEDIA_PROXY_MAX_NATIVE_TRANSFORMS
      value: '4'
    - name: FLUXER_MEDIA_PROXY_WORKER_QUEUE_CAPACITY
      value: '128'
    - name: FLUXER_MEDIA_PROXY_TRANSFORM_TIMEOUT_MS
      value: '30000'
    - name: FLUXER_MEDIA_PROXY_MAX_ENCODE_FRAMES
      value: '4096'
    - name: FLUXER_MEDIA_PROXY_MAX_ENCODE_DURATION_MS
      value: '30000'
    - name: FLUXER_MEDIA_PROXY_TRANSFORM_CACHE_BYTES
      value: '1073741824'
    - name: FLUXER_MEDIA_PROXY_TRANSFORM_CACHE_MAX_ENTRY_BYTES
      value: '134217728'
    - name: FLUXER_MEDIA_PROXY_TRANSFORM_CACHE_TTL_MS
      value: '1800000'
    - name: FLUXER_MEDIA_PROXY_SOCKET_IO_TIMEOUT_MS
      value: '30000'
  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: 4000m
      memory: 4Gi

staticProxy:
  image: fluxer-media-proxy
  tag: ""
  replicas: 4
  preserveLiveReplicas: false
  port: 8080
  env:
    - name: FLUXER_MEDIA_PROXY_MODE
      value: static
    - name: FLUXER_MEDIA_PROXY_STORAGE_BACKEND
      value: s3
    - name: FLUXER_MEDIA_PROXY_READ_ONLY
      value: 'true'
    - name: FLUXER_MEDIA_PROXY_SOCKET_IO_TIMEOUT_MS
      value: '30000'
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

pdb:
  media-proxy:
    enabled: true
    minAvailable: '50%'
  static-proxy:
    enabled: true
    minAvailable: '50%'
