apiVersion: v1
kind: Secret
metadata:
    name: opencode-server-secrets
    namespace: opencode
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:XP0n6xW5Mtpfh4BdCYWcBqNSlfXIpMa1W9TYF4p3bLfmb3VZWLtv6HmraODUALJmL0iKZRUKWFLecq8oWKxncSzokOyjNURTO31+vHHhfBPidQbVNs8HS/0ldmtE,iv:cT7My117kZLL8iQdIG1fKL49j29mUOH43XiQYL6ip1k=,tag:HoY4t8/d81vNTMKONH9LXg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TWo3T3dleEgzWVFBVWRL
            UnFjTmYvWmFrakk4eUxVMFdHU0JVVmY0MlVBCng1dlZSdHJKTFQ5VlNGRmxqeG0r
            VG9vbGJFS05OMG1RMi8xRFN4bFlFUUkKLS0tIE1yMjJnU3lFTzV5MjM2Tk1CTHRB
            cmJ4dWkvY0xsWVVYZlpaUWtYdHRPck0K2ZUizrQrpaABKmcMGe5J5foLcueMATUF
            Ckf6HlnuUiJRjyx+LXx+P24KFQ1fuPx50R5Xum+oRknCbFFtOaGrrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T13:52:45Z"
    mac: ENC[AES256_GCM,data:pSW3b2dlvTR/mA7iDTUEDMSOHd24mFmAoV+SaHnBQjFvsv0tI6quS6SlD5tV33BiUPM+xG+gB3rEKYeEYSpCLyGyHJXbvl9mZwl7zkudoA3N8RiSMEno3FdPmZGWHQKTP+9YEMgnZQx8+lKZ4GflfNO7K55bD4FZcouunwgMKu0=,iv:6/Jo/44evtroA4LnC2NCnvM6900xX8JohWqQUK9/Yw4=,tag:RxEEcdzG4rN3S/maqHzCGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
