---
all:
  children:
    proxmox:
      hosts:
        main:
          ansible_host: 192.168.11.100
        data:
          ansible_host: 192.168.11.40
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
