---
all:
  children:
    proxmox:
      hosts:
        main:
          ansible_host: main.taile2777.ts.net
        data:
          ansible_host: data.taile2777.ts.net
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
