---
all:
  children:
    proxmox:
      hosts:
        main:
          ansible_host: 192.168.10.100
        data:
          ansible_host: 192.168.10.40
        toliunit:
          ansible_host: 192.168.10.101
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
    switches:
      hosts:
        icx7250:
          ansible_host: 192.168.10.1
    vps:
      hosts:
        os3-387-26840:
          ansible_host: sakura-mcproxy-1
          ansible_user: ansible
          ansible_python_interpreter: /usr/bin/python3
