apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jobs-namespace.yaml
  - cnpg-cluster.yaml
  - r2-credentials.sops.yaml
  - woodpecker-secrets.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - scheduled-backup.yaml
