apiVersion: v1
kind: Secret
metadata:
    name: woodpecker-r2-credentials
    namespace: woodpecker
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:tyWy/YhXnToNz0duq5AOTfI9PjaoMN+la28bSFyc60Q=,iv:uwwDRflVdL4blXIV5z8hn+NVgUPhjZJLrkisouMvIII=,tag:SaRE7ykoS7j/j1kAwFG19w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iEltWWGR46jkjnmsoumDFiqee1fkxj7Tzr/LRtpQ25lBT0023er1G6N45tCj4T2ScUUzz/ebJi9trVybuqbhIw==,iv:S0ss7ljlcJlyrg3OU9AARkbiut/7XmyUiBpFCJWNhJ8=,tag:HM+CjBADzJLSQqqIEKWzmw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHhxZWlZS1pBM1JLcDZk
            K0FNcVE2dllmZU1mUkN5dkJob2cyRHNsbldNClpLTDN3RmZkbHJ0TkwySTA1M05x
            OVY5UEhTa2tQSjVPWTJFUEozQnlyUUEKLS0tIFA3VitGTDJNZTZpa3BtR0JYMEcw
            UEVPM1RNL3h4VzZwMlBORWdScGJ5UGcKAfQrZkG1rTHy66Y8ewhWz/XmBUvqgSdJ
            BL7f6pIte8hZmEKHwG3B2zGiEJWHfS610yDitGimUVYFTGOUF4xXGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T12:59:15Z"
    mac: ENC[AES256_GCM,data:WlI79Db7Rrmq2fnxTtJDo+Is4OoHFpF5ZuTmNBMyhtluzC3CR1SWlNpZWzR6xRKYf7XWGNOr8POoorQhpJ0gxuV7PgxLdKsFerUnjbqMUOjPjpfreskZ5u7Lmgj866RiBjgV6shR6I1gr1tHkgry4KWRn8075V6hpRr7W+gyN3E=,iv:UDxlSACLtObWOdAGxfO0KUHUA+Gk8pzkjvS+PSuQJAY=,tag:S4AnekXlw5IJJlBvLgN0cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
