apiVersion: v1
kind: Secret
metadata:
    name: woodpecker-r2-credentials
    namespace: woodpecker
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:DfPFOqtIUgXrhGN3EwHv2x4fjztCi/ymhXEl/N8iqS4=,iv:F/ym85I9yHieY9abDiu/InpCehdf/VqROykHAfxtBdI=,tag:otYN2LIQNDYahFT/unNJPw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8MtZZKX1MaTMU3KGOgWvPB33aulZ+9wWy+StcSvqoPt2J1EezyLm/EByYRlCy03Lk0GW+2e2RtAuDaFzftQnsA==,iv:As6duTIhBvJwX35z63rU7My8PjgG1KQHI4p1XbHYNvY=,tag:j03YOEEfyRu6/1wnMrQjow==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHhxZWlZS1pBM1JLcDZk
            K0FNcVE2dllmZU1mUkN5dkJob2cyRHNsbldNClpLTDN3RmZkbHJ0TkwySTA1M05x
            OVY5UEhTa2tQSjVPWTJFUEozQnlyUUEKLS0tIFA3VitGTDJNZTZpa3BtR0JYMEcw
            UEVPM1RNL3h4VzZwMlBORWdScGJ5UGcKAfQrZkG1rTHy66Y8ewhWz/XmBUvqgSdJ
            BL7f6pIte8hZmEKHwG3B2zGiEJWHfS610yDitGimUVYFTGOUF4xXGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T10:13:14Z"
    mac: ENC[AES256_GCM,data:eBtXrcYPhzXOhnuG8H5h0lh1ScnRQHNIlOKsmE4rSxgDNLYFgdVgAIObMow+JL2hIa1ZJxjofcC6angG4KZyFTdzT+BHf6lA3XjV7IotO9vzupF5YCfg1/iMZssPcLuvPj6f/fuK30bETfbTEweNbhPUBl5eFUomimhuQWgCnrs=,iv:CnGu168tZraGo2V4JGLDL9og1cTgYqOXPYSOzcf7uaE=,tag:0ducMoUmtzCWCFwIdrdyZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
