apiVersion: v1
kind: Secret
metadata:
    name: woodpecker-secrets
    namespace: woodpecker
type: Opaque
stringData:
    WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:MF3O7UH7leoofa7FMoO6Lnfb+I40HGvc8l/K4VBmf6F/HoGCuBy0HsN/QQR0k1DGw5XGrvfrHkE71SiMgTN+WQ==,iv:B0Y0S/iOBsKOsmpO+rQE7dUjUKLt04xBu6z4OGMJ1ik=,tag:fOMVGnkVD7WoOsjnJYEH+A==,type:str]
    WOODPECKER_FORGEJO_CLIENT: ENC[AES256_GCM,data:7mAmF/Gu1s9XqzQxJAqPg7+3b023pyJN9+teYO0WAs+AVWp0,iv:z3J3wPiHZNgP5N3LCsAH0e0PEb0vgtxie6W/5OnirUQ=,tag:fZAgtMpoS4U5Fgbg8oKRaw==,type:str]
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:rnOJ+rO/LSflaYIn/UQtYYUXlYV0pQXNjVYi2ekT3f7yeDhEcASS7npa+8ZKoPft9M/Z2s/39fE=,iv:8H9gqYmXrCbvEW+MXDYzsYw4fovTAb9z047Cyw3cjSc=,tag:HMoTCkTSZSRuJDw++ugdjw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNWJmVWVzdWIrT2twZlly
            c1ZHN0dSSDh3Rk1DRjBtVnhHNVEyTThaa2hjCm05QWJCczJNSkJVZlRxU3JBWmxJ
            MHVGRnJsTWJlby9WUEhzNXpoOTlDTlUKLS0tIHF2TFE2bUFEb0JzMVdkakUxZ1BT
            aFk0MFNtVFFuWTUvc1pNK1IxN1NYT28K26Soyq8ZK/j4awjCcGYrNf+WholLm/Qa
            OTw5sfKzO8u+wWg7JHtm7lenTR4JDRVek45bPmdd0IQCjQGRDvtGaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T10:01:17Z"
    mac: ENC[AES256_GCM,data:j+emj3PFtBOT84vniQNCbx6VuBDB2LqztBNCah1tVYgo/80J7MURCPoGlPzNIvaogavBRyTfx14tK50dGRHOOtfyK4t4btkaOHG2W2+Ry11F+PzkwZ76Fi8VI5IVnSbfn1Ve4afGTS12BzcRK47aNuKkqEtw5k8m6qBoHvW2k9E=,iv:myrf8PNvBkxmrho/Ws3m1l5jye/qfMaIQ5FDdwXI9L4=,tag:ezmAaGY7pPsrt+cOLOF/OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
