apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iceshrimp-cnpg
  namespace: iceshrimp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: iceshrimp-db
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
