apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: iceshrimp-db
  namespace: iceshrimp
spec:
  instances: 1
  bootstrap:
    initdb:
      database: ffdb
      owner: firefish
  storage:
    size: 120Gi
    storageClass: longhorn
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "512MB"
      effective_cache_size: "1536MB"
      maintenance_work_mem: "256MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "4"
      effective_io_concurrency: "2"
      work_mem: "4MB"
      huge_pages: "off"
      min_wal_size: "256MB"
      max_wal_size: "1GB"
      autovacuum_vacuum_scale_factor: "0.05"
      autovacuum_analyze_scale_factor: "0.02"
      autovacuum_vacuum_cost_delay: "2ms"
      log_autovacuum_min_duration: "0"
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 2Gi
