apiVersion: v1
kind: ConfigMap
metadata:
  name: iceshrimp-config
  namespace: iceshrimp
data:
  default.yml: |
    url: https://kameuo.turtton.net
    port: 3000

    db:
      host: iceshrimp-db-rw
      port: 5432
      db: ffdb
      user: firefish
      pass: __DB_PASS__
      logging: ['error', 'slow']

    redis:
      host: iceshrimp-valkey
      port: 6379

    reservedUsernames: [
      'root',
      'admin',
      'administrator',
      'me',
      'system'
    ]

    maxLogLevel: info

    allowedPrivateNetworks: [
      '10.0.0.0/8',
      '172.16.0.0/12',
      '192.168.0.0/16',
      '127.0.0.1/32'
    ]
