apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - valkey-pvc.yaml
  - valkey-deployment.yaml
  - valkey-podmonitor.yaml
  - cnpg-podmonitor.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
