apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iceshrimp-valkey
  namespace: iceshrimp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: iceshrimp-valkey
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
