# SPDX-License-Identifier: AGPL-3.0-or-later

svc:
  shard:
    replicas: 4
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
  router:
    replicas: 65
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
  cassandra:
    hosts:
      - int.flx-nyc-db1.srv.fluxer.dev:9041
    credentialsSecret: fluxer-cassandra-credentials
  cache:
    maxEntries: 500000
    ttlMs: 30000
