apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-webhook
    namespace: monitoring
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:u8MtTlUwM2A+jQlpZVn9CdbGAbaiiRPy85rj24cSQ/WVlMaLaKBF5VlKQvkONlYByF3JhsTKOevTiW2+8Nw4JSOy9ammu/SwfWf6pL6Mn8/bwlbxOoKGsVqgN1ivjrxu8EgtmlMyWjp+hFmfWUWEnc+InQcOjcdcBA==,iv:na6EpTZFLocuRtdf8Nnho5Wr0EpbzdiptQlumcO7vfU=,tag:sQZumV+IJXdrAb84c+jGEQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGJwczlPclNmV0UydlN0
            RnpCZXhFMTRGd2I4aDl1ekNmaUtDeEEvVFY0CkQwUGpTeGk4WWpzV1dpUEVIVWRM
            Ulc5VkFDR0ZLNHJDWlYxZVlPOGxBZkkKLS0tIHhqNEdMT3E3VmtVeUJzT0xsMTE3
            NDZ5SlliRVFITnZBbTAxVy9nekNtRjAKrl30uVBw1qGWmVbTX/Pr+nGYIpzrTWdX
            IWdpmOeZ/0W5XUs+/5n4qBSOuTMXAEwD7Alx8LQ3tj8vjLEd1ai6zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:46:51Z"
    mac: ENC[AES256_GCM,data:mA5WKFjm5Ho4UAIApb2iTWNSNtbCVh5fe34lfXdX2XQoFCWGPurciVpfxMaZ7JN+LaYXiiUYIO2lArfwAcAX3BxAT1wv0Yxuq/fYbM+QG6wk+Ol3beGf0zPP62MuRj8w5QD1Wt9/ABgLl9Y+VBqnpUFJTQXG/8k6VKd64ahlHIM=,iv:yJ99fCN7QHTeJ2Lng3u8XHtK2jOArYkxoWSxOieE0mM=,tag:XLALTH5O1i0Z+MUNpBEpxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
