apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: obsidian-livesync
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:qM3Fg7/Rb1OK,iv:GuspFYdbdFUEEG+HXS86FECTM2AOCkvlBE5yhoyANtM=,tag:EYfcqTMAvifOCObqTmHQ6A==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:Xu7ndbLPy2lRPdmnzxScP2YzGoRfikV/Vg==,iv:3rYeXGeRUtjTqk2Cgwoj2v1YIn/pFxpFzerXyASl2gg=,tag:xioc9nzX8bsQiygopCDVrA==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b0trR2ZrR3hPakxVbkF6
            Mk1rMElPdDFoblBOcjgyelJsT0lnWk1UZUFNClpOSzRNNWhTZkZPYUpjYWFVblVT
            T09KeTdMVXV4TUsrS21oSUl3ZkNKM3cKLS0tIDRFejdacEhWN0VaWnVjTEhvb1RU
            RWVHd3VTaHVLUEgvRlNPWUV1UVN2OUUKc9CTcZ/7yVcVqRPKO6EcVx6yOyAe1xLE
            p0kanHSUahiLapHuc9Jwt3XwfBsH54BvrzQbXeQcxcwRzFNO90g9Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T05:47:31Z"
    mac: ENC[AES256_GCM,data:cVzzf0u5ge9FwCnTe5RNJZ97IZQsmh7w8EScJtQyDnlijpQ4ZgyEMK9u40hcKB/9vD/5qjToSvJC2RvHi3h3eMsv3Z8B8zyuJaLPC0CZDDngcyGIIAdVYph2BCy7VJD4omlPI+2AUBWWhirNj4hWT0L+JAwYArJKCWvyNQLRYTY=,iv:tLflrmimvhuNW+YBgGym0K4+lvI2RaZCpfdHSgaVAZQ=,tag:wgt2qhddtR7t17Pq196oIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
