apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - couchdb-credentials.sops.yaml
  - livesync-bridge-config.sops.yaml
  - couchdb-configmap.yaml
  - livesync-bridge-scripts.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
