apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
    namespace: obsidian-livesync
stringData:
    config.json: ENC[AES256_GCM,data:IHcw+4uuaKptonupnTmDL0PWM8Z1746XH77DIeyUIYb0D124ZZ7F473K0k3KeBmKCs+sH3n0xNQtD48Gkte4ogP1Gt5h2qJeGokRe+pfRzqMVkyFXtnA7WI6yOVjTGR/IkrMh0ccitSEAqS4obU3hNCj1OtvJqUcd6mqEPKNcG1BzcOj9GE0TML9E2Y8zk7cp7ACDjPvNoXdmKH0AIgDTyrb+KjeZmwW7mEYeOIjTQRyZRtfpEwbpA8hUmBEHgCXf4H5EzTplVA7tpydvGGFwhOqnGRJRUGR5PVTQUVdoM/Ylju6wbiN7J3zu3W2WBgdcJ3O33PTWwDCND2FeTgvgv2qUtD8dS+aEJP7zTWWAR98f8l5OOHJ+lgf8EYMMYaGLrQvtbuOGFLkCgalarbCuAcxdWDsms4nRLnOioP2VgSouLPIM1FoZzUdJMrlA5WhwBQmYul75BgHO1OQKXH8fM4AIOk/H8HvmY3i75gfhIIetGoqGKZOnrdHNDBFwUJdQB7zRykYBEg0IOxuoBtioFaBP/8yGjPEH87Vkpm1pbEk5g9lnYTU9WRx3oZ8YpwuVkadiYBs/XzJCfxGQQoOGi5sCu1oYI0ilw15m71+2YslN5+LTNMq+ijkkgrzWjBtzbU1xYGCui0ZG+PMjiY/RJmyfaPzECJY14s9Z/6kaliQY3+dDYarwPKUWphNWvyIyy9gCEv+lJOscBy3EX5b7nLVh7hAlqofRbU15Cx5kRccTIzmeghXZjHkqVy2/i9G+6Is9bBH3W+sFKNpkVKyrFgVX59CKyckmKYEMdwcJqcI4sEs0l4Xaqas2OH+2X7TRbDXe+eag60sbvJaeUBRo4XPFlnUPRD9vbmpjg4yUCjD/Zo6zghGitBAy7RjO+CbN348hfT849+Lymk/w9TpxQbrSc+5KkHfcBeV8B6VAJnKG/PCFYXy8n5c9O0f723+43VnAxnw+cHx9snJLe2mynrTix6dHDYHbuLymxrpDcOUFTOLxkN8jzwKuZySeOlz+4leCNlTXiy81OEBrKRhLy/RFBgwfTHp5jij6UBbIXSCAkkP+3L+CvFzlCoW14LvcMn/wajFLQQL7eISJEm4,iv:+Y8kApF1lOtMS4ovodAseMe95wEiwLYYuR9K9lo4rMo=,tag:FU//q7vEe2OkpkMeCBIhSA==,type:str]
    GIT_REPO_URL: ENC[AES256_GCM,data:ciDAVTi8iO7uVoq1EQ1nGeOj0DFHs8IAAE2sWjl3D+o1w2l772JEs9iaTeE/,iv:6z+d14Vyw3W2z4yFftOB0voIarvtYzTgbORpZz+wdio=,tag:A6l/eB6uqyLWJqxGofAr8g==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:bCFMPO9Y7KWyg74CdhRpyJFjzpUIcNXu67gBihB0zMRWVIPUbiWsyImHOfdyOF3SIqfqpXnvdVF69iwt8e9lCjN/SZHfVPJ8KIP2fI3Plh7wUy0V/J46m48SnCPL,iv:VeSnM76bhBHl8Y4bd50K67/VWVTKiBlqOlyBi1BPxnA=,tag:8rF3qKWUWEusVqWv6fvzNw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2pKS2V0YlJlbnZUQWVq
            NWlQV3Q0azB0WnpUb3dZL1Vhd29VWjNMRG5vCkY4WkRnb1dlTjdwMHVKbVA2RStD
            ZjNUbk1PZEtPZ3grbEZTbTBpb3VxeVUKLS0tIDM4Q0ZnOTBYa3BzMklDRHBCeHFa
            dzdtOVZTZVE2RGNjSUR6WnR4NG1IRm8KNOux2qzogCqoCDgQOiiill6KiTEXbdA9
            K6G3JCvqMY6vR8ggj/v9SCftl1TTGIUJkS59Cl67uZVYqqoUjlf/SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:20:20Z"
    mac: ENC[AES256_GCM,data:u8PBgQYLr65iuqoe00nx6w9IRbsCVy+gHC8dPvfxyEpjzoetant6weyiLqgVJcCfX/1EPDtlzcA8Z0zoz8j0EMu8YrAN2lAVo/4FSSg6zE7d7SDwkj9NTbdWd8liQP6Z1ZpF7j2UaALi1APkT0mBx2jkWPSGSic7573QlEpWHgw=,iv:nt5wsK1NrphELQAEQK1TFEg0TLDcAojR8ermipkYvCM=,tag:dQVnLThY/ieFb3wMPT2F/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
