apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
    namespace: obsidian-livesync
stringData:
    config.json: ENC[AES256_GCM,data:O3pN49mT1NfT18FciR6j2sj3zuo5tEBZZ77V8B6RYSph9QNUV4DEMMVxwURM5vivITLbvbSA3xQdAfoowl3weJLwkfTNL5aVrw/DSZ306+hQFOn+qCRGI3FMLFrasTcQJNDuoW3ME0fcdDQYVdK29Nf9b4ptvyWUVMUJ+Dx6ILxHbvUhdYHc47q6M58QYkLUfsCP3XXLaSJZ2T02wLbXt2bhMGcB4zuZ9r7lqUTUTn8kOyHHXx1U36ET/e2BKY4S9GlgEBbgnq/IAvmncMxM4k0FESZF/Xu/OBY1XjIDZoqMo+ApjActqKc15dI65sG0+VnkYTqMyF63z0i4oA9CeWrXC3AhJCmHQ8Won56g8KJs+x3H3YEvmIOykuYFt6oaIE9d3kjMxB5yPDE7Xq7sJKWhBnZY8jo6oeR04cmTi8WuAWChZNvlIJlpkdkQ1m9ksSxFNnr8D513YdJ314+EE/FYnJZWGCzFNoHZHkTnaTbep8NukCnZF1Br1atgHdCeWYsh+lRqkgJps9ntgXpD0S7IesDNA9Cw7Ac3gcqGdkQ5XFbp3UhTFrpju4UNjtaaMvhOk3fOwMs5reKI/J0pP84n4Vc5dyfLfjccub7c8KoJLnMssHBGq9UvLywqV+52yVgXZr3MxJEyL3BDW5MBHfUeIzjsXcLn7glT9yKt1Ausi/xMuKiG7DpmZCBR+vR35elQhBZt3lC16SbifIgsyZlp95GaaPJurD3B453jIcnF7wEjnvoAoRWbG0eQn6CfmSQWh07W7qZZETWJiV4h5SVZA5wPYLnpsbiby4MGr4TafiJx0wseHemgIsCqGAHTaTn6PnX8FzAJ8+3oVtJklvRo4zYR9fHOCNicodJ/cehgUZhU9IiU45EEWv7hUhXPm1/ZXyA/BlvN4orAWkGcIxUHYN5WIh66OUGVp6ibl3Yjr0Sf9+qALIDs21YLdnpHrCqK4V1yYVMQrlIMHAGh+WOsyrQAQMsl7XY+oY0SNKzzqvZq17ubpHVX+TsE88ngx7pyBFRtN+u5bDQMeQTjb811TO6d9rVgsZDaoIJN9TLqHFBcmE5RoaL4jmQrcPqYPxMYsFrTt0fichpFWlR1IqJIDiY7sA==,iv:gNtt6dQqsOdyxsUN3e+rYxYmmgXFBvJMhp1/Wl+S5zA=,tag:vpVTbJdOl93e+CE1/BZSUQ==,type:str]
    GIT_REPO_URL: ENC[AES256_GCM,data:ciDAVTi8iO7uVoq1EQ1nGeOj0DFHs8IAAE2sWjl3D+o1w2l772JEs9iaTeE/,iv:6z+d14Vyw3W2z4yFftOB0voIarvtYzTgbORpZz+wdio=,tag:A6l/eB6uqyLWJqxGofAr8g==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:bCFMPO9Y7KWyg74CdhRpyJFjzpUIcNXu67gBihB0zMRWVIPUbiWsyImHOfdyOF3SIqfqpXnvdVF69iwt8e9lCjN/SZHfVPJ8KIP2fI3Plh7wUy0V/J46m48SnCPL,iv:VeSnM76bhBHl8Y4bd50K67/VWVTKiBlqOlyBi1BPxnA=,tag:8rF3qKWUWEusVqWv6fvzNw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2pKS2V0YlJlbnZUQWVq
            NWlQV3Q0azB0WnpUb3dZL1Vhd29VWjNMRG5vCkY4WkRnb1dlTjdwMHVKbVA2RStD
            ZjNUbk1PZEtPZ3grbEZTbTBpb3VxeVUKLS0tIDM4Q0ZnOTBYa3BzMklDRHBCeHFa
            dzdtOVZTZVE2RGNjSUR6WnR4NG1IRm8KNOux2qzogCqoCDgQOiiill6KiTEXbdA9
            K6G3JCvqMY6vR8ggj/v9SCftl1TTGIUJkS59Cl67uZVYqqoUjlf/SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T09:33:34Z"
    mac: ENC[AES256_GCM,data:rrYz405J0rYZWR859Oy7DyCzyN280FX6uMAFj4colUMbdYVACV2RNZs5yhfPg4PFshTLG4JBMBmCz4kX7wKmfBCghwGDhPHkMcNxOQzYyA4ts+cEglkI8J2GXxZEh+ZHtzqdTqmqyTgoLETD+SOi8By0SgwFbzOhcfm1tkAx3Wc=,iv:QRl/Lf/WJMeLXX7hALek3qWDbE3PFA7dRo9GFgg0zlM=,tag:sDPWCUmrE9s4DIgONjPPEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
