apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-livesync
  annotations:
    data.longhorn.io/number-of-replicas: "2"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
