apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: obsidian-livesync
spec:
  type: ClusterIP
  selector:
    app: obsidian-livesync
  ports:
    - name: couchdb
      port: 5984
      targetPort: couchdb
      protocol: TCP
