apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:AGKysq+SXcBVOodiU7lZwHk=,iv:ywbVN+DIDuvIc8gnMi2n3lAFgeDxgZHtJw/b12eb6H4=,tag:9MFhYBkj6Bpkgm6eDHT8Ow==,type:str]
    client_secret: ENC[AES256_GCM,data:qlPaIPBNgU7EaHwIFz1N7YuN7eph4u3oV+3FESiGNNJ5MxEjkxLUSqfNZcSiW1H6M13AVl6D1iUN9PDeJo0D,iv:sRrq/NVpXL2ZsUU/XBnxZgT9MjdZRqQXEny+mAWsFTM=,tag:Zu/cKGPsHtevAcY2TemINA==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL3FQZS9oWjQycXZXUlFB
            c3FVSGhabzNwNnlYcnhweWo4NWdybjlxdkNJCmMwNk82MzdsRElrMlR6bHgvRE9O
            eHE1VzFkV3NqeHdVSDV6dEZDbTNpbkkKLS0tIFY2YnFmY3k4TjI1QjZWL3Rra0pp
            S1diVTExYkx2UzF0MHlwSjl5a3ZjUDAKscALFG8rvi4/ReCosQUP8/Gnpboz8rzo
            Dk+btpEEOtxwSNRwBhlvUCPZ+36Tpmj0hWcjdsW1kktnwj9ZSW9zEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T06:22:47Z"
    mac: ENC[AES256_GCM,data:3Pl7O+5QLyRGpAOVQ2+V/N0oM6OanmRCWRrQsP8fohiHtMzzAuXhkH+B859MXJCGdXZS9HETRZBuAZbgp8H0sAioauGgiEOkued7/C15aKaZVAzAA0VqqpcEuZwmozATkIjCja+W1sxa+zidqzRS9+tfqmpIekv9ZGZoFP61A/c=,iv:ysQMw/E9RzFPYgQbWm2jMd1GN8fgv9dQJiP4z9zrb5w=,tag:fAsCdzY0pZMnj5i5SAsQIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
