apiVersion: v1
kind: Secret
metadata:
    name: hermes-lepi-secrets
    namespace: hermes
stringData:
    #ENC[AES256_GCM,data:ggRe/22k0wj12LTBeVWtp8+kq2KF/c9tPLPv0NjPhuKMUjzvJGPZQEnAVO9MTVBSJTwRZi/VQloibWcmSxsyyA2ZVGVdDg==,iv:oaIFwtDe+Nyh1X5jWjLB1QItn21/uT5AoDyS7D7fcjI=,tag:/jTx8ifpAXoK3DWSop9gkw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:v+0mnYTTokxi00UjaOsWm0nBKKCSxt6WLI9yow==,iv:oq9AvE/30/v6qFUohgW71WGV1lzd7+j7ElT/Hloi2TM=,tag:yVoGUIU/dfhPn2fktj06kA==,type:str]
    #ENC[AES256_GCM,data:sXqBxF3zrOc/CC15grnfEqRE,iv:YcfOC4blsFYOLvpiJq64S1NKW3q1jgQpe0LTTEsYA2o=,tag:50lwGKrVlh8lfApY+hBMZA==,type:comment]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:B3AzGFEKkQvYV2OzjeOOtQ1I55WQnUIRq0ijYmSBHdHfm9zoyqYFveI+wSy8CtPOYTKUogIP5T2/an3mOzc0Bp3OIbm+NqNc,iv:H64vl5gQA9L/0PNkL2Zbr7ip1ZlBT9PccZtBtWyKXr4=,tag:OeoQ4xlBSD85x5ypx+2VZw==,type:str]
    #ENC[AES256_GCM,data:6BLhWQXP6VCRcvnW7pmzG4qeXbpw6UTLn9oRWjWcLVfZGTfmdYKFEFBOD2fIqnotHJHFlbCM8tWj3dyETZY4pmI=,iv:N5nL1dZzTxqVGlIxIaIlZxn3e/acYwx3WKVbEa0mJYM=,tag:TIPopnTxVkyHaYc5pCejAA==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ks28+6DRnth5mUbRTj1h2Tgt0ACM/Lv/1joaKtzez8Xklse0UqcerDcRaPZTC37mv1hgheRnJBxkH17cv6dbcKBykCxWJOfAjkdQZ7PqUk+EYzr9lSLl0vgDkKrr,iv:MpqhY9A06KfnEpq7+bTk5kE6OexV04PWqvKujqOHU5k=,tag:NDzbbchipMT5GHVX7tI+ew==,type:str]
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:/L2kDd0tjQ==,iv:4V0oCkdhO1tm/tr6+QUIuDDj/mxM/rYe3fp9rQrJ7gg=,tag:58WwOFI4/ofYM2uHQ5/m/Q==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:31si8nxeD3tZ3cJVBHFjWXTEoDz/DKGkuBoeC3bw3A4mUqJxj90t5qzQ0SYMPnwLT1s=,iv:wNh6etfDLTvSJHe6muchGdY4Bmd+Dp4oiJnfpyohAVk=,tag:eqVGsBmYpuP1iKKRGzj/+g==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTHdYY2s1Ni9NUkphV3pW
            SWxQZ0VtRkpzbW43S1BHMzg5SzR2dHhoajEwClVSdzR4bitpaDFuUHEyUXh0enVn
            b3QxZmIwaW0yNEFhZmhQR0UzYWVvM1kKLS0tIFIyLy8rc1k4ZFRoVmVTTjRNbmhu
            YjViTHl2SnptZ1lUbVRTaVdEeUh1RkkKEr3LporLbIevHkIl2tGKlYMpbcV6pEfI
            lSBlalJMQyf9oK/KcOK5in34htdsbMtCJ7CeasYzxjPnsjIeqwUklw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T14:37:27Z"
    mac: ENC[AES256_GCM,data:Pat6Vk2RAAgP24QBB9Y1gYPo86a/CTw44u057OLBJMX6RD8EaciRQi606damhoVdoY2L0q9TJd74qaFV2L+898DXDABWoKh/lFI5E5+JYsJPorzFAU9bbsFADUiyWtf0L5tdmeXd79+fyiibNLLViGONXTCUkWCW2DnsJwfZjPI=,iv:2Ya1M0699HFwPT6MSHjjHg6/HsH1CFdhMoJ5RPNp30A=,tag:j8ty5xKs38/GYwXFqRDkmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
