---
apiVersion: v1
kind: Service
metadata:
  name: hermes-lepi
  namespace: hermes
  labels:
    app: hermes-lepi
spec:
  selector:
    app: hermes-lepi
  ports:
    - name: http
      port: 9119
      targetPort: 9119
      protocol: TCP