---
# Timezone
proxmox_timezone: Asia/Tokyo

# DNS
proxmox_dns_nameservers:
  - 1.1.1.1
  - 1.0.0.1
proxmox_dns_search_domain: ""

# NTP (chrony)
proxmox_ntp_servers:
  - ntp.nict.jp
  - ntp.jst.mfeed.ad.jp

# Common packages
proxmox_base_packages:
  - curl
  - wget
  - htop
  - vim
  - tmux
  - lsof
  - jq
  - unzip
  - chrony

# SSH
proxmox_ssh_password_auth: false
proxmox_ssh_permit_root_login: prohibit-password
