---
- name: Configure ICX switches
  hosts: switches
  gather_facts: false
  roles:
    - icx_base
    - icx_vlan
    - icx_dhcp
  post_tasks:
    - name: Save running config to startup
      community.network.icx_command:
        commands:
          - "write memory"
