---
- name: Configure VPS hosts
  hosts: vps
  become: true
  gather_facts: true

  roles:
    - linux_base
    - tailscale
    - ssh_hardening
    - docker_host
    - nftables_vps
    - haproxy_minecraft
