---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-system-trixie
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  storage:
    size: 10Gi
    storageClass: longhorn
  backup:
    barmanObjectStore:
      destinationPath: s3://forgejo-backup/cnpg/
      endpointURL: https://db189f6278d9d9fbdfd8dbf99a5e8c95.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: forgejo-r2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: forgejo-r2-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "8MB"
      default_statistics_target: "100"
      random_page_cost: "4"
      effective_io_concurrency: "2"
      work_mem: "4MB"
      huge_pages: "off"
      min_wal_size: "128MB"
      max_wal_size: "512MB"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
