apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bszRCIhP4zTLyemMPA==,iv:U18ohSr/pUh7aH9dXlZZ2CbYxUE75T+xJJ9C0s3yU6s=,tag:H5T2xaCYyKJMczOXEKSIig==,type:str]
    password: ENC[AES256_GCM,data:lLU+HmO+5CvuNSKX7rRwTrCRMdyT5ZEYeeyOEAQXobE=,iv:Y0EUPS0tUnYFbAICkZQVSFgP9Qx64E88Butq25Orqgo=,tag:4kWatRAfyFKyAiQ0L4um/w==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSnhvVjlsZlF5MVd6aUcw
            bWVCMWxyNTlGc05LSEpzSGErN3hOOVBSZzJRCnNPU2pabzJPS1pZUmVXU2xldDFP
            bFhCcUNZWVVwR2hOTEFIaFFXaDVMSGsKLS0tIGhaZ01MWVEySzZKS01aellRaFFz
            S2pXVFczKzFSM1ZzK2VraVkwRmJMNWMKTLxz5Oo3HhZFy04H5E8ZZln0tETMHibl
            rKN9SILYHAwXAHJLMO48uSO38gXVSDudNe+jfpDG88C55xOjBKpjNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T08:35:38Z"
    mac: ENC[AES256_GCM,data:gxUxTHncnQkO1jVSnzBE4fHFG/E+u/pcj/752KtCYZJ6HfovivMkIiaU5hXNKvsnWzckW6qVbTYrCNgQdo6HwdClrfEUuYtiVfzG5xTVtr36NVTOHE5lkCS6G3vt6MUK6WKLs7xbqIs1/JcU9lIqDGgz88l4XIxKTK0Uu0OToFw=,iv:xmnyuJi/OkUX5azXBZfetoA6MD8Jl5wen15Ou8Cga3o=,tag:ZEjpDT8yGu8VdIkC3R5CFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
