apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1VuPLU0=,iv:FMQaCT9k1OFIIp6qPuf04csHaV8W6OZJFHlHhVAgJas=,tag:Wz+axbv+FbF1Quh862lAKA==,type:str]
    password: ENC[AES256_GCM,data:lLU+HmO+5CvuNSKX7rRwTrCRMdyT5ZEYeeyOEAQXobE=,iv:Y0EUPS0tUnYFbAICkZQVSFgP9Qx64E88Butq25Orqgo=,tag:4kWatRAfyFKyAiQ0L4um/w==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSnhvVjlsZlF5MVd6aUcw
            bWVCMWxyNTlGc05LSEpzSGErN3hOOVBSZzJRCnNPU2pabzJPS1pZUmVXU2xldDFP
            bFhCcUNZWVVwR2hOTEFIaFFXaDVMSGsKLS0tIGhaZ01MWVEySzZKS01aellRaFFz
            S2pXVFczKzFSM1ZzK2VraVkwRmJMNWMKTLxz5Oo3HhZFy04H5E8ZZln0tETMHibl
            rKN9SILYHAwXAHJLMO48uSO38gXVSDudNe+jfpDG88C55xOjBKpjNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T06:13:02Z"
    mac: ENC[AES256_GCM,data:8Wja6o5uoDyW61mxpEzDtGfpAaqye9sHZC94jjlbrR5HIXFM/m6AGcsXiqsuOmc4a5bf+I+3Xo/cxYhlaod0fP8l/8+v3uel1NZbTjzboOpyz/PMDCkGaAkT9JAObKB4MDSkPiTAg7Fs9Ca/qLRlCxNNlvKRaae7vLnhe9w2ne8=,iv:lq/PiHoiE2mqdkH3N6I7hoSQXHr3W8w7iTzhzOJ20lM=,tag:BEtIOBcFlwhnyYG3a6z56Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
