apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - r2-credentials.sops.yaml
  - valkey-pvc.yaml
  - valkey-deployment.yaml
  - valkey-secrets.sops.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - ingress.yaml
  - ssh-service.yaml
  - forgejo-secrets.sops.yaml
