apiVersion: v1
kind: Secret
metadata:
    name: forgejo-r2-credentials
    namespace: forgejo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QTX8eRlm8G77bWoY9x+cs9/HGRnxSjnIdq53iOTy2tk=,iv:NJhUzuxSXmlIyBonmFTwN5oxVTNUEw/NK/o7oMuDhwg=,tag:BClbdLUmEGSDSunV6U/HlQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lzOVpacftYZwjPt+RxBvvw3S5TYLsDn1zwAAq5ICJ0KqO5le2X7ukcuafgCdml6azX7srgcCoOn4GzKbZ378MQ==,iv:O0vPf0kRqib0WQ3s9jf/gxnqwy5+aZxTdyXdDKJfTdg=,tag:rjv4vtu9loj2+FKVb657gg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V0JNYm5YNXZkbWxNaTRZ
            Q094VUo4VTRhWU0yaFVqdkxnbmlDWDh2Z1hRCmJEdFdNTFhXMTVGemI1NERGOGlr
            Y20xSVlkMGR2eFI1aWhiRWNVSjNwNVkKLS0tIG5zSzV0K2FnNU9uc0I1Uk5IUVg4
            aFlXS1NoOC95Tmdscm9lZlpXdm9LKzQKYnBPStqV6MNmaJBbtpjrOzbUNVFxcY3K
            5mqI9R7+0D3yaOsnraM2sIz1HNW7oawuRftp+sVRHS4KCYUJo9uMgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T06:13:02Z"
    mac: ENC[AES256_GCM,data:dRamjpCAWNIS45KSgburj/xrky4G4vu6FYEuKSGlFDxkwzlVJB/kc8IFkLoFM0HBlFnZa+4hQfLJsV8XRxaT1PxYmi+DgniD2QDQ8hhODurPWg7IpAoYnjalRJTG9iHlLxEKeZEWairKIGchMy1LwanA8jAeSgO6UQoKANSvyXU=,iv:x21g88jSPzGsFaB8btBNqWPXj3Z5OdQ/UcVjSwUptbE=,tag:RGOfCdeCYZhNnYAMJ4bF3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
