---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-db-scheduled
  namespace: forgejo
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: forgejo-db
  method: barmanObjectStore
