apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-valkey-data
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
