apiVersion: v1
kind: Secret
metadata:
    name: forgejo-valkey
    namespace: forgejo
type: Opaque
stringData:
    valkey-password: ENC[AES256_GCM,data:TQk3KkXuueDxzwbhZ1ff4UAbANZbZBUtVAtFLY6cSVA=,iv:iuCXI+q2utm4OtweJuxcjSu4dElmSNUNs14QbjNLV1A=,tag:iQqSIklhKVaw8zvD63OBAw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTy9UQ1pkTGFOcmhQMnpY
            UjZ0c0NvMC9OSnFGU0dhTm5vM3VoZm1RelFVCitnWHB2RkthTThWWDFsekk0SFpH
            Rk5hdFhJSmI0VW1ESXBQSjFRVlBSRjgKLS0tIDBpdUp0eFRtakpjWC9WTXhXRENn
            RmlHcWFUT2hFSnI5bW5DWTFJUm9YVEkKTgcSVDwoBYkyRcOS3paHw5eHcAynbRpn
            KPqkKJvMg3xfCGvhVyjbLmQ4thLHlEFakEG0NRkk/X99EwfgJ5y15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T06:13:02Z"
    mac: ENC[AES256_GCM,data:7itkosPNyDUMCx68dwYp0ZYJzvXVm+SUK7N7LUE6Dsu4WLHarGZLK0k5ivwuPULuQJg7wp714LIIqX/iQwdLuZLgqFaF98uz2MSWwRWYxNpwpMJflugq5stABg30n/fM1APYPO+B8B70jujOIxDJpDN5dyszKNTOtUrYLQuwZ3g=,iv:4tZkvZzMm9/bHxaQ+7kCJL1NdZ6GakukvVcCcJfcQXI=,tag:11CZvQsUwuT1iZKE3IWDvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
