---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    tailscale.com/funnel: "false"
    tailscale.com/tags: "tag:nextcloud"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: nextcloud
      port:
        number: 8080
  tls:
    - hosts:
        - nextcloud
