apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:HM44f0c=,iv:Uxk2hUmoBY1nxRZLgY8PFvP1HV0hx0476LRyelt500s=,tag:wXMc32o7dSLbUDYqhWPeNQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:de+ZuuOHfIRLqKX4vjj8+UBL0p4lcr3wgG8oyRkgspO6jPA+vpQabooNKTZpUVgf,iv:nw+QXMR66atnVYnsLnqVz1oG0I+964myFj5AtvSF8VA=,tag:OHEDYtY6UUXbEqYWc2i6ig==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TDBmTGU3UkJqWTNNTUtv
            Wm5oblhOSmVKWGkvTzRtc1RYbXZITUdBcmlvCkhsS3h2Zlg0L3lOdVhnQ3VnS2d0
            VVd6TU1qWUl3ZGJiZWNrM0tEZG9tdjgKLS0tIDdFRy9zUElLSHg1YUVSZEtLZzlh
            Rkp3NCt0TkwveHpFM3UxUm04UFdYbFkKX6TlOSGHmtd+UnEbXGQK3eTh4hmWaDZU
            hkM3WRXIbeuvjD++p0WRmCgem02E+wqNxLcH3CeyZp/gRgYuUpgRFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T06:11:29Z"
    mac: ENC[AES256_GCM,data:hbbV7BmHQ9XbNjGlmv31yvKXuBv55zX1pgIbSsc6SXvBk1aTgVrlnkbwVu3M2nhXb+jWZ5qT7P6YugSDozpKLCw0d0zykTryQCtsBcftffM2dCrRGTRx2JUdgSeR1t3Z7XorwSmyvfjEiAfDRXinPNyIqMQLvmVVkFSpybFTLmY=,iv:iyDy+7Ed7bkoOtvgZee4Z0TfJDJ26qCBD7lrVkdo6yM=,tag:noCFcqBsEXmfWuADFN857Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
