apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-valkey-data
  namespace: nextcloud
  annotations:
    data.longhorn.io/number-of-replicas: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
