apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-valkey
    namespace: nextcloud
type: Opaque
stringData:
    valkey-password: ENC[AES256_GCM,data:n6Y2FgxezrPdBpznzDduWoTpyNxC+dswGuS5QlRlRGIupwDY968Z7Q==,iv:1qbR3HzFOB/MyB+u5Vu7Qs5Na4H/kcNposSJJZvoJ6Y=,tag:co8HKn/wgJeHLIufuzyj1A==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZXlteTc2Yy9QamFrMEI0
            Mzd1UFRBSmM0WWdVa3h6VFVqeHZwSGk1cHhrCklibktHTHhVQ3R2cEErUldzaEQr
            eGlLTFRCR1p4ZE1aSUFkczd3NEVDdEEKLS0tIExaMUNVSXpEczBZSTFoM3Q1dXVH
            U3FNaW9IYU9sOW9aeitYZ25EcElnODgKFpx0tkvgFHpfNx6JnmGEFjibsricpSPF
            krTACx/rLiQa1IHNPlFEura1ivvVYuZqiVRWpzVwy0+OLVY+tVXqyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T06:11:55Z"
    mac: ENC[AES256_GCM,data:Uaqldk/m+a6dn41hSdJzbsvWpz9VVaiU9IJKo6YwwmwxssM25YUqon9qvmcR9SSpcDs1ILna5WysbiJqFohoqyufeJH3UyretoRTwSghJlOVqyRzQdUOkLIocboRDbLPmmfMDwmerTiXAhIoEKgHpV2IdbPh6nCk1GfXDvTlhGw=,iv:jEL+z0cZ28yh24OVikUmuN1wiv9RXLFZh0drkyl8XMU=,tag:YOqvQdJNoiqAfdmwOaU4rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
