# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v2
name: app-proxy
description: Fluxer app proxy service
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
