# SPDX-License-Identifier: AGPL-3.0-or-later

global:
  namespace: fluxer
  imagePullSecret: ghcr-pull-secret
  registry: ""

app:
  name: ''
  image: ''
  tag: ''
  replicas: 2
  port: 8080
  config: ''
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi





  env:
    - name: PUBLIC_BOOTSTRAP_API_ENDPOINT
      value: '/api'

pdb:
  minAvailable: '50%'
