# SPDX-License-Identifier: AGPL-3.0-or-later

{{- range $name, $cfg := .Values.pdb }}
{{- if (dig "enabled" true $cfg) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "fluxer.labels" $ | nindent 4 }}
    {{- include "fluxer.selectorLabels" (dict "name" $name "context" $) | nindent 4 }}
spec:
  minAvailable: {{ $cfg.minAvailable | quote }}
  selector:
    matchLabels:
      {{- include "fluxer.selectorLabels" (dict "name" $name "context" $) | nindent 6 }}
---
{{- end }}
{{- end }}
