apiVersion: v1
kind: Secret
metadata:
    name: openclaw-home-secrets
    namespace: openclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:wPlS0j50ZV+ehHcvkuXeKhuSLgfY4DPw/TcZjq4rYuHMbRxBGGH6i1D5BKmQ768STfq3Ac6G8zebzbIDYNSt7/8MTiK4mQ==,iv:9407B08qO2HScJXl0wrkcOLlHwXNxfVuDt8klKe3saA=,tag:g2EGA+z2swDeFLXwLwyeRg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:QO/Kz3qDiUa837Q4Pzq8MdIzAFpOahvYow7+R0AgIobnwhboVhxquEH61imHECLjWoFbA3wdqNFqd+YFoYwrFGF3aaAztNFIQlfpaRCgXuo3U5M1tsunuAPNUb6T,iv:6wZlKpG7VTuJCIsqn/sI0W38CRje3zwRUiQqcDmiylg=,tag:e70ybge6Dy4eYlJAaxwjEA==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL0g3K01lSzdoTkp2UDly
            eGxHeUdsaEt5Z0I1YmpnUmJQejNSNzg5cjEwCi9Ia0lvejBnN0prQ2QvR2ljcXRV
            UE1oS2xlR1UxSGNrbGlTZzN0dE9aQnMKLS0tIFF3MkIyYVgvUDZyRWk4MEJCYk94
            dmJqUGdFMUpNcm5pemcvT2NlS25ML0kKFxssxT1W6knnVyKVMQIEwMOEJxDrIMJO
            vgsSodNAoZ0EHvyIXthkFh3jBnzm0YVNT/MOKg0CVsdPqxP8yy5ftw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:10:38Z"
    mac: ENC[AES256_GCM,data:iwwne+E5SEuevqw5kPkPEo9qWya2XC2YK60S7olcKPDrNyoKTxm7NleoVKLAqtQLjDwJy0gPx8f1xhXDsWkskF4IGfS8gHlnEPrnY0R/Hqy9h8xumcX//fUsK3OmyfpfZ4hEVxFwQvfLoBOFmpGLvqMDN3fSNc7skq7NlgUyJbs=,iv:9DoCtSrP8zXxovzwVnFiajRTUgb9Q8PfxEKIm4/dXvk=,tag:hrq7j/UXuLTYEiGd8tXWog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
