apiVersion: v1
kind: Secret
metadata:
    name: openclaw-home-secrets
    namespace: openclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:wPlS0j50ZV+ehHcvkuXeKhuSLgfY4DPw/TcZjq4rYuHMbRxBGGH6i1D5BKmQ768STfq3Ac6G8zebzbIDYNSt7/8MTiK4mQ==,iv:9407B08qO2HScJXl0wrkcOLlHwXNxfVuDt8klKe3saA=,tag:g2EGA+z2swDeFLXwLwyeRg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:QO/Kz3qDiUa837Q4Pzq8MdIzAFpOahvYow7+R0AgIobnwhboVhxquEH61imHECLjWoFbA3wdqNFqd+YFoYwrFGF3aaAztNFIQlfpaRCgXuo3U5M1tsunuAPNUb6T,iv:6wZlKpG7VTuJCIsqn/sI0W38CRje3zwRUiQqcDmiylg=,tag:e70ybge6Dy4eYlJAaxwjEA==,type:str]
    PLAMO_API_KEY: ENC[AES256_GCM,data:bpC0NLTyjFVmGhnpdZw0t/m9ML8HUdm9hl0dwkwbIhaSSeHNEK5rdKnxjbG8FarKWzD4PwWV6nX8hQlsjpFFYD5T3dsd6tRU,iv:Zwrd4Fub4h4yCMj/sqj5GeL5w3gXtkfaro2r8BRWfxA=,tag:JSlcd8AQguPD3UVdr1vGBg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL0g3K01lSzdoTkp2UDly
            eGxHeUdsaEt5Z0I1YmpnUmJQejNSNzg5cjEwCi9Ia0lvejBnN0prQ2QvR2ljcXRV
            UE1oS2xlR1UxSGNrbGlTZzN0dE9aQnMKLS0tIFF3MkIyYVgvUDZyRWk4MEJCYk94
            dmJqUGdFMUpNcm5pemcvT2NlS25ML0kKFxssxT1W6knnVyKVMQIEwMOEJxDrIMJO
            vgsSodNAoZ0EHvyIXthkFh3jBnzm0YVNT/MOKg0CVsdPqxP8yy5ftw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T03:44:33Z"
    mac: ENC[AES256_GCM,data:dvnroSU2i6gqITO2CkHHur+p9JUz57eUQ+kgWBqg68uLUAdbjv23lfEAA592OSmjI3l9mXhATmlNuTYaH3eb6GzGfoaXUc9gyGVjrL/v/Yb3KjQPjt5QAi1pS6zxuYqVfFeB/T36bvSQmyXSmGMYfJG6PznniZVsaIVncJ16poI=,iv:vqImPf7yL/GNxKNx1kB48l26GqiWEywNV8O/f1KRMIE=,tag:pkD7CP55twN0x0JoweplZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
