apiVersion: v1
kind: Secret
metadata:
    name: openclaw-lepi-secrets
    namespace: openclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:mC/O9ymUC9vDnEj6U10su3qUOc4TKeONFve9DfQeMIYQKAXkPnH+XNCKvKJv4CJXrxiYzCds/YD2lztj5SqUO73uBKmghA==,iv:Uq3FNB8bd/023OvqLmMBFt0Z9Yx7Qmryb7Mt8GUnlDc=,tag:0Uuhn2JtVgXI4agg8rH/EQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:qMu1490ObQQyNJ0AtuOFsTGszQBeLiS4zgEizBH7XFJJJ90ZlZL2osNBNuK1UtPkbffcz5fbkDcUGW/y6A1nUQ7QgKx57OYc,iv:4SFL3MhdRzNdK84bYTyLmiEAwXNcA10x8VPeuEpr6lo=,tag:nXFGeVmk41Jk/j/1BzMFoQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMlFZRW9WTGxJMDZNcDZQ
            akl0RmRUWTllNEpta05VMEo3aTd5SU1GMndBCnFMR0cxOEYvTzc0blJCa000VXJD
            N0kzN0hobmg3NHNaNXdSQU12dUFkQ3cKLS0tIEJCdDNsRTRkZExNOG1rNlk5RTZy
            d1JicHl2d3BXd0VyY3Y4YnpwS1RSY2MKDPB6TPhABcwXOSlRa9UvQ8scioQZHC8N
            OG4oF15Ynxqe5Mjx4LVo4uhkrZHpN1aix4sfqqLrfN1xNQEEPzBtPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:15:26Z"
    mac: ENC[AES256_GCM,data:V4VQV70Np68+wN2ID7o9qduFgCmb2uWTNuX/c8ZxvjgKx+CN18KwrOtcQnZIB13ElYWy0gQdHOR2JsJJFsoibQteH1p9zEtS6s7cgmsP6c2AcQ7AmEl3yepBVTcbmLRcCU++V4fdDTkxpexrcFzpdT6vgRtuOOGIpW4TSlPccts=,iv:0aLI7B+sRH/HkfBMt1ktFhrXCFD+QHWP3B7FrMqrlew=,tag:IOkI/Oo719TGsjc6TR8qFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
