apiVersion: v1
kind: Secret
metadata:
    name: openclaw-lepi-secrets
    namespace: openclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:z+DbKUan2zsdkEtVKz1nI8Qk3NpUOjVMNyepXj8Zsu6g3vLN5rWn0A6L0ZC9Pv+i974o2BtqKzZcfExuz9BWQCJv3FWr7Icb,iv:ac9yKpcvTwnFoUKti4NJ1jVp21oVCCNu+lmizKLLLv8=,tag:Lj/PRa7wnvLQNeA7Kh6qtg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:qMu1490ObQQyNJ0AtuOFsTGszQBeLiS4zgEizBH7XFJJJ90ZlZL2osNBNuK1UtPkbffcz5fbkDcUGW/y6A1nUQ7QgKx57OYc,iv:4SFL3MhdRzNdK84bYTyLmiEAwXNcA10x8VPeuEpr6lo=,tag:nXFGeVmk41Jk/j/1BzMFoQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMlFZRW9WTGxJMDZNcDZQ
            akl0RmRUWTllNEpta05VMEo3aTd5SU1GMndBCnFMR0cxOEYvTzc0blJCa000VXJD
            N0kzN0hobmg3NHNaNXdSQU12dUFkQ3cKLS0tIEJCdDNsRTRkZExNOG1rNlk5RTZy
            d1JicHl2d3BXd0VyY3Y4YnpwS1RSY2MKDPB6TPhABcwXOSlRa9UvQ8scioQZHC8N
            OG4oF15Ynxqe5Mjx4LVo4uhkrZHpN1aix4sfqqLrfN1xNQEEPzBtPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T07:06:58Z"
    mac: ENC[AES256_GCM,data:HvD36wGsHqokcZVk5PkklytyVFqhOm+ywazbjejjLpL/DcNxJKLBkH/wgS/7mkzOv4i/HFaai58GDKelmokrnafnyyGUL9vCfuBPfaykpqV+QrWTc+NSkvrcaIOuvpy7O/EvrwUZ9GUgmkSiuREC6wdoQLPWJcCgvOKZ6pvOJ24=,iv:AlROL3Ccni0vuDmsA/kKkSJdlrtyEMLWdoN2G6lGY7c=,tag:ixduEbUDTrJcZITAvUHkVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
