apiVersion: v1
kind: Secret
metadata:
    name: openclaw-shared-secrets
    namespace: openclaw
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:k0qfWLEoiFnfDp3C61QklphlKhDOv/JOtR8wtAU7QK7ye06/5w0BBNr1To98IoyGmABa7eBxSWWOEqGEFUvyEykd1KZXhZBKbWOekR4vRshEXPmMJeP0m13afGVxwMb0O427oJGwoEkDMo7fl/s/xxQq0LrPeP9yZ5v6x7vOk07niET4LjZPVAvL2jiTNaUfWG7LPfNcHX3aK1XLjFkx31R185/Uzf/hYFsE5juqLzgJII04lHS0CEklcQT2cJ9QvbFk0LIxqhitcn01pkYmI/Madk5wtNAh+paEOVeDNVTBi2DDdCugRM3CrcmPyaOBChwfR9S9ov/rWiVHvfOFSgb6pmpHZyRjyB/B9pKY13LoX4R3n3kdY1DNyPLne9AEv4ZVHcxx6JSaf6Hcg8jZv4AQx86lYCNyZqRpOomDfkCX2qbY/PE62TtS0x7Owl98Chti,iv:0ZHucg6q5qCOEPFKd3OVjaM57zOBdubUiay3bpYYO5I=,tag:n2vr8lzvGJZhqeo24FRwjw==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:22GMheqMTPEkMxkvzQ/kBeD9ChOGO40C3DlHMe9jHk5wTIa2YZr+Jzj3wrgktw==,iv:c2gZEtoBpWZ0fXHfhDDmqMr5U4YdMtvDzsndn52ixxw=,tag:hfOaWfwnQZ0UyqvTCtiJHQ==,type:str]
    WEB_SEARCH_API_KEY: ENC[AES256_GCM,data:ww75DBJdEoPLNQMUDCD8S8yY+qqn2+xfNn6IPr+6Vw==,iv:X5eDntjfq9fCxbKjgLi15T2f0dfbGjmBL6JdWYh0pJc=,tag:cXpaQ8u1PSyLiwcH5g198A==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEgyQUh1eFhsZVdVcEZs
            ZjB3V0VVYmxwZU50L1U1TUZDY0FyNDhJWFdNCm40Y0VnRmhoTDJwYjlVRXhmT0ZD
            Z1RzMjVuU3VLR09vZ2pDQ1gzblAxN1EKLS0tIGU5d1ZOOGZHNkRXK3lPMWZFU3VU
            YWN1cW5oQmtuSW1PTk5kZFlUUnNEQm8KZeXih8iQfEjVLFgGsuHKXmKz9w3qxjQh
            Xa2+huaGT+o2bIm6qeN+BbIQbM2U2LraKwhMLdV2lF7PgCz9lTjg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:08:12Z"
    mac: ENC[AES256_GCM,data:vPHW7NnjgeIr/pWvMj/qk+r0gMs/g9Y77DNZa91L7jFY5b+7RcojjfKAMYXkU5K/vAIGfWtHXoy4XFcmgPO415VmpESOc6FydZ+jHGD7hJsrdUMQyuQOiwpkMwEVFg+dQ8W1GGCyUDhOpz8CXY6JX/5K6W3RsF27NKxC3sscyvw=,iv:AEwI/+3VIoA+pFtFZC4OYry0nJbzSBfj6OsG9GDYwpU=,tag:9gNMeXiRWDZ7uO+jyLiAEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
