apiVersion: v1
kind: Secret
metadata:
    name: openclaw-shared-secrets
    namespace: openclaw
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:kjzOrbmCyMlerkGnTnI3azDrDupqg20+WiW3PbhiVf/kb3EHZwaZxg==,iv:CZkR7HuIF9TGdSPtcCcSQGasTBGt7l5lAQ/pUXdEPlU=,tag:KXTgPMhs4W1Cvj3VYOrJ1A==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:22GMheqMTPEkMxkvzQ/kBeD9ChOGO40C3DlHMe9jHk5wTIa2YZr+Jzj3wrgktw==,iv:c2gZEtoBpWZ0fXHfhDDmqMr5U4YdMtvDzsndn52ixxw=,tag:hfOaWfwnQZ0UyqvTCtiJHQ==,type:str]
    WEB_SEARCH_API_KEY: ENC[AES256_GCM,data:ww75DBJdEoPLNQMUDCD8S8yY+qqn2+xfNn6IPr+6Vw==,iv:X5eDntjfq9fCxbKjgLi15T2f0dfbGjmBL6JdWYh0pJc=,tag:cXpaQ8u1PSyLiwcH5g198A==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEgyQUh1eFhsZVdVcEZs
            ZjB3V0VVYmxwZU50L1U1TUZDY0FyNDhJWFdNCm40Y0VnRmhoTDJwYjlVRXhmT0ZD
            Z1RzMjVuU3VLR09vZ2pDQ1gzblAxN1EKLS0tIGU5d1ZOOGZHNkRXK3lPMWZFU3VU
            YWN1cW5oQmtuSW1PTk5kZFlUUnNEQm8KZeXih8iQfEjVLFgGsuHKXmKz9w3qxjQh
            Xa2+huaGT+o2bIm6qeN+BbIQbM2U2LraKwhMLdV2lF7PgCz9lTjg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T07:43:58Z"
    mac: ENC[AES256_GCM,data:MmpGZQzt93Acr7Abaz46TiA+Ndpdmx78SpbdykvDo/rGmF5WbGtowgxRQWkmDGVCns9CTsTHpkptDxnka87UFTUQE0Ee7pwktql7Z9frok1Kz+4jXUyXQwoNwXpdtGm5tXwAMzyvHG5KO5kep1eD/lD+ooT5C18ffm7nMNQ55yM=,iv:09/f/wpx2KijXN8T3Ba5iCJb96hxOLJW03jLWvR6maw=,tag:Sm/vxqvN9UnWpOzOMt8A0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
