apiVersion: v1
kind: Secret
metadata:
    name: openclaw-shared-secrets
    namespace: openclaw
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:975BIlRNS/VZGpEVQJwbeUmr9gt0eg9j9dkiW8ojqGxhSsCLIX2WV4hAEQC2PUMp8N440liRdDv3SdSdvgGqYGje2v9LPnd4mrrJwD5zKGhNYrAxHz+m6rwvXDdw,iv:UYzlxu32r88EuBSor7kCqvjKsU7DzW4FjswQ6pXLjxI=,tag:y9NVOmZA76HcKu/+FIsFZg==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:22GMheqMTPEkMxkvzQ/kBeD9ChOGO40C3DlHMe9jHk5wTIa2YZr+Jzj3wrgktw==,iv:c2gZEtoBpWZ0fXHfhDDmqMr5U4YdMtvDzsndn52ixxw=,tag:hfOaWfwnQZ0UyqvTCtiJHQ==,type:str]
    WEB_SEARCH_API_KEY: ENC[AES256_GCM,data:ww75DBJdEoPLNQMUDCD8S8yY+qqn2+xfNn6IPr+6Vw==,iv:X5eDntjfq9fCxbKjgLi15T2f0dfbGjmBL6JdWYh0pJc=,tag:cXpaQ8u1PSyLiwcH5g198A==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEgyQUh1eFhsZVdVcEZs
            ZjB3V0VVYmxwZU50L1U1TUZDY0FyNDhJWFdNCm40Y0VnRmhoTDJwYjlVRXhmT0ZD
            Z1RzMjVuU3VLR09vZ2pDQ1gzblAxN1EKLS0tIGU5d1ZOOGZHNkRXK3lPMWZFU3VU
            YWN1cW5oQmtuSW1PTk5kZFlUUnNEQm8KZeXih8iQfEjVLFgGsuHKXmKz9w3qxjQh
            Xa2+huaGT+o2bIm6qeN+BbIQbM2U2LraKwhMLdV2lF7PgCz9lTjg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T07:31:00Z"
    mac: ENC[AES256_GCM,data:lq63BdxZZf7zlx4eqV+DJJlr+/GzEBBoNPEhCA9zEGftQogi4m+xQALdEr8znGxWK0vJcPyATPfNsNu0tEkDDBqvdiVOxc00osVbXgN7HZXXrBoK6uidHKB4/UI6QXuzzYfzuiyWQ8SsbpfS1K8dUNs9QEmuwVDHl/CVs3xzUZE=,iv:519Oo1h1wqiZ8qJG5vNTHLo6ymfe/ueF86oabTQAbno=,tag:WeJ8BOM46zVpba6/DJsaKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
