apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-home-secrets
    namespace: picoclaw
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:H9W+0GBjRaP9xlqBW9J7INIK3M5YwRWFdcMYb7LBFiypLbPbuuY5boPRGjUcsU9XSy237A0bpNz86sCoYhUVt9+og7wL44lioMHzoZWNlB/GkYFRPYNGbf7QCIOs,iv:eFifDhBxB2XRmd1z3vfL5jBi4fDYMouP2zQLNB+XL8E=,tag:j6nwmwJG9Wh/KzwF72YlMg==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ0l1RVBIKzdaa2NudHRz
            YU9GK3U4M2pGblhWWXUyTFdET1VuMUgrV0JNCmlxZGFFZ0NZVHBYeENuZ1RYMkNC
            OUZiZmNZak8zRUk2ZHhWYVBnaWQwQXcKLS0tIGpVQ2grM25KTlFIa2JOaDJ6dGpu
            NW9RZjQrcWttUVhkNVJWd0dndk5zUlEK4D09EU8MMvp6jD40KeMYWT6Ko/4Ae7Tk
            XXuzBIeap3CbDDcK9NpMHMmOonevPqUqMeO1FOwhHk3/wgRLSUOMMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T13:51:47Z"
    mac: ENC[AES256_GCM,data:bihLEkdNLHGKVFGO6hyut8C9ymgKI3K32hlIHk3u6rdrG0u2vzY2LCZonSH4rRjR7c6MYpSosolD5E6YKTzedyNBqke5uHxibMxV9jU93BdOjXSVhwh9pWsdFGLmjfIoh9bbMw5FRrC9p42GoBZh2aCYDB35W3ObFlGVzhDQ5QM=,iv:wSr2V2AtxmJ/8LtaXCcYayDe+wfUAxwq+SKFMjO3BsI=,tag:9+XhHJprryBoLAN4quETWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
