apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-home-secrets
    namespace: picoclaw
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:H9W+0GBjRaP9xlqBW9J7INIK3M5YwRWFdcMYb7LBFiypLbPbuuY5boPRGjUcsU9XSy237A0bpNz86sCoYhUVt9+og7wL44lioMHzoZWNlB/GkYFRPYNGbf7QCIOs,iv:eFifDhBxB2XRmd1z3vfL5jBi4fDYMouP2zQLNB+XL8E=,tag:j6nwmwJG9Wh/KzwF72YlMg==,type:str]
    PICOCLAW_LAUNCHER_TOKEN: ENC[AES256_GCM,data:deXagH8Q4cyIU66xkzXIxXxM/cYC1lw9Kh0xxkyy8SaT1X4hX34bp0utWqL4FRwh6/42/q4eJWcqplgeR+YYFQ==,iv:xH7OWrYEq6uOkeIazOeK67NejXC2su1hDWp8H5fy+M4=,tag:J3MK2o7Lf6f0ScUjRnXBCw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ0l1RVBIKzdaa2NudHRz
            YU9GK3U4M2pGblhWWXUyTFdET1VuMUgrV0JNCmlxZGFFZ0NZVHBYeENuZ1RYMkNC
            OUZiZmNZak8zRUk2ZHhWYVBnaWQwQXcKLS0tIGpVQ2grM25KTlFIa2JOaDJ6dGpu
            NW9RZjQrcWttUVhkNVJWd0dndk5zUlEK4D09EU8MMvp6jD40KeMYWT6Ko/4Ae7Tk
            XXuzBIeap3CbDDcK9NpMHMmOonevPqUqMeO1FOwhHk3/wgRLSUOMMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T08:54:51Z"
    mac: ENC[AES256_GCM,data:zYmpoeZ9LSkSMieHUu8IqSOVJFFbnpssFy7Hpw30ngWLobZjTK45bUlvkCmxkWuzUCxkcTaB5UgMOHuqG8SO+/aCyC4R8OLNd06JrkK/ICo8sRQe9VhZmf4O7ZtkaybvjLB2BuB9Ql7GNMhpbBCKhCdpZdRpMVzfxxHIjoCY7xo=,iv:yH/XwwjPSQxkiM03VgloZxs9kCTihurQSkUurQVcteI=,tag:lVRI2zU/aw8m2I7AHu7zWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
