apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-home-security
    namespace: picoclaw
stringData:
    security.yml: ENC[AES256_GCM,data:wmHPKatmfcNl5+GU0LVxi/df8ZysdL8fnY/tvUq2XgCkmCiZNtswtYQ+oqMDP8AAs6F+gR/JiAR65pM6wJdw5JZvveCZ/NdAbI0C6JDBdhfBEAiU/+Nhmcag69Vt6NU22fyXqBcfg0zJ28uQUz4B+JY8TDJCNYhFjnpCP7Ouq6ngXoo+fN87nuawjTSa7c9iPp6S11UUm2+9Jccwqr++Vf6EMjQhmiY/Yfc+3cSP8B2LAirtVdf+HDLPXVIbM8/FIDwSMKI9n32Z5KcHFwNWGLPNTMwNx/fpftU0AlaFjZqylqKmPdaCSAqboAQil9q3S0MocxqhtTZqvpFflzxKn9a/Mp3bSPglpHAUH6++O4+zEJ/qbntHok2xTXmQ7HiIPWp+Vg==,iv:IyBinI7EPDmYO6VeYAgJBKg0pti0ZT32n9rhwe4bjfU=,tag:Uo9+o8fAUrNu30M+G6VPdw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYzkyTkQ1LzRRek45N0hF
            U0RJS0tMZUJ6cXdMcVBPVnJ1dUFoUHlKZmtRCm1ydm16NnhRS1dBQUVtYVgvd1My
            Y3FMSi9BOWFBL2g5MWc1Uzl6SnlTOEkKLS0tIGJDWUFWSi9UcksrcjFBSDU4SmNG
            MERsckdVdSt4emJiNFVRVnNWVmFQZjAKqoH/5W3oY+FAoP3SQF4RY2QvazNr7XHC
            qWHy+btdDIG1GWte2bPTGkZc35LRjKEzA4eq9R5DNFs0pO2XtvrfBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:06:55Z"
    mac: ENC[AES256_GCM,data:fp2GZGpwJ9un09j5mo8vCBoWFJV52KyAx0jtWTh7nXh30JlWUHFixjlb8yKof6Trzu7LmC5ls0TT0sjx0x5b9tvFWyoxLuMFU8Q5LblVmjWFI+fRUQDu+qDxIHz7zDn9SUoajeu1eHoJkVZ2KCxRlW5X6vuSqJm5WxcVq/Xz+9c=,iv:Dbs59jYDeAcqv/FNfxkiKFzh/3CUOhTd4kQbXyQAsUA=,tag:DUcI5TUoekxAMjlvlvgGfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
