apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-lepi-security
    namespace: picoclaw
stringData:
    security.yml: ENC[AES256_GCM,data:67xxQMgGfy1pdpLA/Szbxj7qh90MvW6P9y3g+12hlHOC1tcKPsQUbLK4xyeQtgn2vXjTcX7eZSQEI3ZKdj4Bzh5j1Uzzgrd7aq0CA8zgoi29tKFa9fvKqraVMmdHWnvHYgEG1BVtC6w36H9llkRjtb1w1MwW8bZBbNL+RmVYGap+c2o6gDzHugSRU5NU0j9tFLRD0OvOfDFwF4dZUttps/07W/SUibmLUMYpMzFrt5Sb/dRtjYBE3k/3mfzsCm/O+pzt0USYEYp47ViMbVY/wKHkaCwSpfdAsooJY+yBWQKCsruPoCC6lHuuS/ei+89rP2YEwwYskIcXzzyNKTOz7NcJ+XiWfT00YBMYbGg=,iv:XOE/9ijIQQRy8j6clFwJBQpVzfwOmbN3Vvp9maHXLew=,tag:/SdcIlz6SP2vaXrcHZJLSQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUG1oNkRnUk8zY1hWV1F3
            ZW5nUDhudkdJWktIaE5JUXNHZ0hsTFRzVVdzCkpMTlo5UHdrbG84VnRJT0I0QThY
            YXduNUtvZ282U2Q5QkRTdnNyVDZTQXcKLS0tIHdWWFo1czlycHJtSVdDK2k5Umxr
            a3NicUQrVjA1Zzh5S3lwRzdJOStnbmMKpDIjz2Ab8TgqU2iv4zqd39qUB6Wv1WS9
            dFTp9i55wJJy5STc6ur3n4EAQUMcJVycZaB+7sIKc9Z90NQkYPHXXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T08:53:57Z"
    mac: ENC[AES256_GCM,data:fKTYFl7x1YZQ7XRH1jpXno+aDg2p73bFARQp68/MQRCpB6pA6LDRmsx48zSIJXdtNRC8LppUdYxppDoNQdjSx1Qz+oh4J12hGx/Hl8tKjE9P1fKsyq4vyoZns3Pwd0YoqXldAIYv5iUpvM1ZQ5r/UY1mISa0BluVLmdIJjedHi8=,iv:sNg848ayK82sxU/WiReYqXM6meECu5s59Y8kLR+W1mg=,tag:e+Wi1R8bzm/zEJTW1xzIuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
