apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-lepi-secrets
    namespace: picoclaw
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:pbGS7CyFGaOgP6PTgI85/vpJYPiufcAoAU1FPY7tldPmH+KgfPX3MVmxDmzEi+93t3bsBYJ0IR9k1WZVu7Prmw6mvv7B4JfiE67+5g8s0epZJY630uvE/8bRkuYW,iv:uJ+rlzpLFh3jqktbux0RAqpYpUSDQhxGltHpw5oEomk=,tag:h9QKvNY7SI8ASQinD9a8tw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcFMxMjJOOENOVXlDOXZG
            cytwMlRFOHNMTUQ0RmdYQ2hvR1VYbTN5U0hRCndtS29qbFZiOHdnSWV1aTRrVlV0
            Mm4rZ2Rlb0prTmhHRjNXS1pHU0w5L1EKLS0tIFZjVndSdUtDamU5aW1xYlNFak52
            SUxQUTVROEV5RmhmK1NROHFQckV1a2sKri2ZxHe6GUQTLsQdbsBnbBhJ89yP7XKH
            nIxRve5zs6s7Rcd8TdJXBoqdeWW8Hbip1EcKB9qltV53ShXIaHPfNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T13:53:24Z"
    mac: ENC[AES256_GCM,data:L5zbIaxU+XOD1FQX4nB+bWaJqNBdgrj+rLrt2jzqKUKv26eMQ0VL0jv/LwodWwHZRku3VF6SsTIZtH7hS/xaqCLGhFjrziJ+C9gK+U+c7eETzmtJk14aR4Y3L61Sx7dy1huPelOhXnIa4vWppYFFAq1DotTFjtaguEi9dFBL+Pc=,iv:vRtl/ToHegaXw2jytC3MPFnhwbIWPo/7gAshR1czmrI=,tag:mmOBLMtgslxtnW7zgJxPHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
