apiVersion: v1
kind: Secret
metadata:
    name: picoclaw-lepi-copilot-secrets
    namespace: picoclaw
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:kiw79qIAbY/mfW5L2vG5U9DStIAkBodg5aUAzJodZ8VGiRfewAMDoA==,iv:Y5AOYXb3NyPdz05qC+qxhLxz5hC0guygfY/DHUVNlEY=,tag:gPwvpIhLtAg8yYFyPBfhDw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU3dqZ3dkT3dEL3BNWWpV
            eVUxUWlZRXZKNWxLQnRYeUFBZ3UrQUNMa2hvCmR0aS9JblRkeVBsODg5ZktncDdR
            OU5jYUEvQUZOYTBNY0NwNjVMbGFZeDAKLS0tIGJqT1RmZmx3TnZYVVRUQ3FldVNq
            VHVYOU5SNUVLMVFmU0RjVnVScEI1ZXMKdYPrEuc+wnLXxwVTH2eeqGnpnXd8YSr5
            3YwHR5KMsvdVswdQ55CX/Pgc0YZmDELU9BqXhHlhZlC44qVEPaDPng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T13:11:35Z"
    mac: ENC[AES256_GCM,data:CiEXr/odlutJjsEke1dX9BNWRU1pJa5LrAbigkQTezi6L4lD0kwAl263zNjkcN9z8D3eWRWcixlUh4k+6Uq3t2OWjV3aOqsjArSjPsuO2kZwQl7z/sfZ4OWDMzo+4jfKCC3t3aTrGB4WELYgjzLPJze2pyjesWWw8MtfAX7HY40=,iv:oTc4pgF5PrPq9pyu8CWBumnr37EaY5/gInuYE0juAy8=,tag:iPdbJzIZfp4Lru6zmsl4rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
