---
collections:
  - name: community.network
    version: ">=5.0.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: community.sops
    version: ">=2.0.0"
  - name: community.general
    version: ">=10.0.0"
