apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-home-secrets
    namespace: zeroclaw
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:0M18BZSdSpxbYOtJspKEMDU0GI3841PPxNfbnR/neXt6zNoFSkH6sI74jVT/yKhEWfFPUd6OX7NUqMDBMeaD1+aasExg1F0WkQ==,iv:B0KFOCqYR1W2PqKoZALIsxNFBnroIrC72V7CZMDM1MU=,tag:fVM1ULz1CVWdib7aqwZ/mQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:FbD+r69JHXBPXLcw/OOI1TVnPSpa/figne4YXpCvlLXldRpEmzfnBOGAxbgkMNglNS0j4M09IOiSYmTKlXIEQYnS6/DUXlvj3WA9YCsLADQkeuPCnPKomtl2jbUF,iv:wRyV5E3jdynEvJPKC8yooJFqWxlNguzhnBLO3RSomss=,tag:v84a08uRBywsduN9vJrjMQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSU1kdFhHOTJkRmZLWlB4
            cDdmZHZhVDdUK1A2N053Q0VaQWoyeWpqMnhRCk83YkowSGcxZlo5UEluS3VtWFJj
            QWtndVI1NDNEaWxjUTY2QlF3eWJ5czgKLS0tIEZPc3NUR1QyT3cxZGExWllRb1RM
            VXUxVlgxQzAreW9qays0cE1DSHQ1MHMKNwjawIKPxkkn5kmCOI4KboQpE9V6BnhE
            SQP26KUE7s95IsdK6IgeC/t475ULCz+UoSPnafX/8bsMj0M5+iO4iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:14:19Z"
    mac: ENC[AES256_GCM,data:UkxYIaTgMGRLeyr7AC71do0zdxKLMQPgDJcNd3h+1wqudtMH6XXLriKWVoE7UI82wuVvddNLydkvRGFO07W+gnHqN1OpmzgPjBitDAJo0XiMre/hO5TmjkMOHvjYe/BmY1mcKohj+3eaODkbDCBxDz3Fkvnr62hUpYOhMftkXaM=,iv:o5OrwK7jCBMyganZVfMVYVW6PsYy//xECVlpgdyn+WU=,tag:Nu72DTfi2XPpkCsSdTKcBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
