apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-home-channel-secrets
    namespace: zeroclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:E1rbfRefMGL/8mJnLEfdmulN7m3FR+GroQTsrgqrzMqyi42jPdRb51HarQtpYNx1j5f2MRKtGq/Ic6bSo1h97OUSPa1VRQ==,iv:Ki5kNCJRHYimTGw3Slve6grOc4bkejtrkRCkf/6pNJI=,tag:ymLnAgH5JCRMxFGLLE16zQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VXJuWEI0K0FYdWNtb3Jx
            ZElQWDVDSWVOVHRzcVBCTGYyVnVaVENiSlFVCi9DU1RVdTZNcyt4UGZxQ3NscTBl
            SnpPUkYxQTErMjJ2aXVpejZ5ODBnOVEKLS0tIHc5WDI2T1BFcWo0MXJBUVA5dVpr
            MTYvS0dkV3I3Q2tQbVlKMFE5MXIzdjQK56pdLbB1B/Sj6PW3LQyA/UMKreVbjrbj
            lJ7s4T4sCIefVloekTnZs/B5TOW6Juybftkg4YMy5rA5KZB1yz8uKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:14:14Z"
    mac: ENC[AES256_GCM,data:Cj3SDOoGqQy+kIfUOoljd5y8sUoWvY+WC5MPOGBwtGPlp8VwS2QL6Tehh8x6zlQg3jyDFxde9zXxeELq0QzTf+xFhVNWwpH0CJQ0BGlKyMQOYGcvw/0JmcsW9DzDLDtdf8BwTje2o3e9N5VI5OjJPngt1697T6hHv8NMglGavT4=,iv:NK30Z7PEM3bS595AG/HL735owAt7BhG04K5Sj5xhfSM=,tag:V6Sp/BbKTTYmJIJOw4HxCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
