apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared-secrets.sops.yaml
  - home-secrets.sops.yaml
  - home-channel-secrets.sops.yaml
  - config-ops-skill.yaml
  - github-ops-skill.yaml
  - helmrelease-home.yaml
  - ingress-home.yaml
  - lepi-secrets.sops.yaml
  - lepi-channel-secrets.sops.yaml
  - helmrelease-lepi.yaml
  - ingress-lepi.yaml
