apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-lepi-secrets
    namespace: zeroclaw
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:eybGHdjbgBfHGlWBQwEspSA5SLTJHfptHEG4iYqs9W8J3a6ynD0ID3fDsDodGRjCp7C7EQhWc9jwwVWp+AZVrTZO8LoRfv8nWZ8D6gc405tAoYMkxyS/pKGhgCfw,iv:NswsqlP6jUqf+l00wRqjeSnhEp5sLh2vIYhIHqnaetQ=,tag:GBvC9VTMMnx/3DyaBjGhRQ==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXpNSGRLbzZVc1JJVk9Z
            MGppVEVycHQzc3plajRBb240dE1KcWk3TWtNCkl3QTV0QkN4R0lJUUZBdHlwL3Uy
            V3c3dkxYV0tHM3l5VFlUQWV5RUVOVkUKLS0tIG1FU2dxSWVFakJMZGpqRnhTTDVJ
            OTRCcUcwQzM0aWhHMThuWGZSYnZFTDQKxQcVa+CqRzhRcjVAfgXUl9BMiRuFxGiH
            bjJsZG4dDGAg0Ldx+rjo0eYsqX487BcetyVd7R57d42gFZ1m42zEHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:14:34Z"
    mac: ENC[AES256_GCM,data:P8Hxugb7XKE38J/H8Hl+m3bQz4a7ZZ9xKo/1gYsoRbsTRJI8jKxAAguBvVnyDWCVq8kk623sBRTSTLKjUJq+LX/B2JkrXiLHls3t2F1STZYpPpuJ2PU4FvFC6cDtjYZBMP4OK9/9ctrTFhnF/Qjg3799D7I26srrSajENCfYtok=,iv:dLUhI11NBs1Tsy1j65fWGRJ6UHDl2VRUXn/B0dx6vKw=,tag:V2hIzfWeBjCu7hhEVfESFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
