apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-lepi-channel-secrets
    namespace: zeroclaw
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:LeRkBmBkethkOM4dkf4hCFgtozYC6my4QbTCq1f7h06roo9kFId5kz3BRDA3sZugHg6MxavAKjcP6KOmEBmnP2HZg4qp8j5D,iv:ghOKy8OvlbLKqv9JgL4vQ4fsE9xwS27eP5bVn4jry0A=,tag:t05iv3HkVWCQdpvxXxskcw==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOUdaS0J2Mlh2eTF0WnUw
            L0RrN1B0SkFra2tPRnF1LzA2cldDRFc5VmhvCjVwSWxTQ1BDdld4Qk9aMStaMEtp
            WFdRTTNWaUJnTTE0a29aNXlpQmpyNTAKLS0tIHZrUXM1N2FLNDdoYitKbUNhNUZv
            Um4zcEx4S0R3RDdubmtxWFFiWlNwWmMKnox7842gyG1G8GUta7gZTgGI4ypbi+n9
            ZDsu52PLVgtUHjaD0ADyQB4s3ZoyCxRB9Kv06TYEGDInHAI/PK9zuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:14:27Z"
    mac: ENC[AES256_GCM,data:eyMg5FoiAqQNam72Q3c/fsERwb+va7bCKuIC/nBOdlYRitb4NLeszow2uYdHiU93d8jycT/+FTfARkdmbxac/js0vTWFqhjttqO7hrderKyxTzj/c29qyu6oWmX8BgDx1mMao0ZCBoI9XsyTJtuM9Y9Arae4j8d1vqjoQsDVKaI=,iv:K0ii/NvlEMR5pFROfsGj2XOFuf98rvslYCAcj5PrpXU=,tag:vALEhPqIwULBeUqrSisv8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
