apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-shared-secrets
    namespace: zeroclaw
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:gebrNOzUc9J3zaGSFyUwBXUSsfwq86Hdzr6AqJLGLxCOtbHhTpY5pg==,iv:35r/6q8Io87kTXLS04mBzH2Qj0cFID5C+lrlL8Lf14I=,tag:xWAJbn6lDyp1yep66BxSYg==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:g5mULYAqEo1VUPEQ6wRFrpqb0WR/Xfhd/fx9A9/cpDggHbMrkTBkklFKwQBXyQ==,iv:r5Izc1Qnh3AfoxLoZ2AraSB5bcxXvirxgGuCWUoyPOY=,tag:yh98fAZ42Y0lFqusfdp5iw==,type:str]
    BRAVE_API_KEY: ENC[AES256_GCM,data:QX9j1eSmRr5UXWvCF8AWTTkLb9ANXjMMJvNC+9tQqw==,iv:5v+zcX42L5mOYh0cVVYmQVjyvKwwGWp1BFzjtn6lq2E=,tag:aRhj5xcdFLc5T2IliWJOow==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOVRpZFVLRXY3YUE3NkZq
            UWV4c3FtTk1QY0NlTDFPVnZ2Y2Q2S1BtTUQ4CmNGV1c5SkJablFoQkRqbDkxM1c3
            NHZ4VkxWYnhnZ1diUmxwVWY1dE85QUUKLS0tIHFPUFRxZVVpcHdDZmJrNGJHUllQ
            bVZKa3hqQm1YTVNnT1BPYVY5dXFLWkEKWnhVA90AsFp0KGqKM1wXtopfXYlQd3Ib
            drIF/J6MtsfhjkQR+osyoRg+9FgFg22B3NKxlFJDMq3SiYzfcLvLjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T13:14:38Z"
    mac: ENC[AES256_GCM,data:6J5ZxCUGpqKrQlc3ZpZzDvcf9fTaCym+07s+zEG/Hj9/xWyp7tS3PtfbpMDoSBEsySYRrG8/fYMomB6Z7DEDyAkcj2UCuOimkZfV8+ohATMaki4PscSU71iMm7U1++nzgYuiJOWyjktd2awu9zeiJ7HQ8HSnxSUF9RqYmcGR8dc=,iv:pwdmLmnF7nmhsicU6fv7VY5i36NqFvdw/stzUXUZJ0g=,tag:QxU6RerM/XPB0VusxP9t/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
