---
- name: Set hostname
  community.network.icx_config:
    lines:
      - "hostname {{ icx_base_hostname }}"

- name: Configure timezone
  community.network.icx_config:
    lines:
      - "clock timezone {{ icx_base_timezone }}"

- name: Configure NTP servers
  community.network.icx_config:
    parents:
      - ntp
    lines: "{{ icx_base_ntp_servers | map('regex_replace', '^(.*)$', 'server \\1') | list }}"

- name: Configure DNS servers
  community.network.icx_config:
    lines:
      - "ip dns server-address {{ icx_base_dns_servers | join(' ') }}"

- name: Configure logging buffered
  community.network.icx_config:
    lines:
      - "logging buffered {{ icx_base_logging_buffered }}"
