---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${tenant_name}-deployer
  namespace: ${tenant_name}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${tenant_name}-admin
  namespace: ${tenant_name}
subjects:
  - kind: ServiceAccount
    name: ${tenant_name}-deployer
    namespace: ${tenant_name}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
