---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${tenant_name}-quota
  namespace: ${tenant_name}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
