---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${tenant_name}-quota
  namespace: ${tenant_name}
spec:
  hard:
    requests.cpu: "${quota_requests_cpu}"
    requests.memory: ${quota_requests_memory}
    limits.cpu: "${quota_limits_cpu}"
    limits.memory: ${quota_limits_memory}
    persistentvolumeclaims: "${quota_pvc}"
