apiVersion: v1
kind: Secret
metadata:
    name: longhorn-r2-credentials
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JRJdo59c3NxgPG4L7b/m1GfsM3Pz8RVhfCF5RTdS5Es=,iv:0v21ygX7aLIivo/OIl1rw9iPH3p8TcB9yyoHcdOmcrI=,tag:1DAIZbMJqm5KfOGpi8pVzg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VwDst8Qx7CuufmOdXKJxWjqu5gk9JmUknnk7iTWViclHU9OJejrLyz2pY2PTHZQ1MAnkDEIh8HH16ZHQu7U/lg==,iv:+qkGa0bo7Hv6gpzcmITP5n7AHF4yz9s431I4yXU4aos=,tag:aSPasqaCJfw+ekLCxF7baQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:KjnKHRBB8nOo2QL8NAYAYz3NLrK8sdrowIMP6+mYRTp7zpJjcp+CJUWX0ozDXHUG8FZxc89HaBFCyMJpnrVZZuA=,iv:RU7cp35kzpuO6h5ElGeiu9AMalOLzd918OA+VAJb1MM=,tag:TQI92Jl/34wjvNlV7c3t0w==,type:str]
sops:
    age:
        - recipient: age1zm9leyqvduytw07xpq3e53zp337wqslj5gx6aadwr7fxw0nv6pxqczcm55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnRvRk1FUHBBUXgyeTM0
            TEpMZTF3ZHdtUWR0WURsOUFKakVmV05BckFjCnBxWEwvUXhBWCtXRnpCbElvVEVt
            dk1CYjlLSVhJL082MVkzMEViNHZqNlEKLS0tIE1FVWJPaStlUnExcVB5RFc3U0ZK
            RUdTY29qaEVGN0dBUlJJMCtWdUFFNzgKuLHYofSbgxIzeAGC4Mu0sfEQ7L1LqN4a
            jyrP/2q0SjDDctSCMx8JPSb9ZS8FpQnNmPJnyzdRKLjbYUyFheWNZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T05:56:43Z"
    mac: ENC[AES256_GCM,data:9y8MKXvx2hcBtRjAJhCt/M+g5H8BWgDeky7w9qK3GBfcGOsLBTr7TdfcVM3hrXDPzA+ILOsPZjFwO6jzKMc88XhKwHnFhs/TjUjFQqB0R5ngQYsGHRyw4at+nYi333tFFueScdsYCgDsTphG8EiLcB5GlmyLd0Q4QlcXrfYvCH4=,iv:hgyVpyYrAql1Fmk2uJwNVst21PFjr1pd+I0/jXsMBMk=,tag:kC7VuEmzxMd34o41gXD+HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
