apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-backup
  namespace: longhorn-system
spec:
  cron: "0 0 1 * *"
  task: backup
  retain: 2
  concurrency: 1
  groups:
    - default
  labels:
    schedule: monthly
